### ISSUE TITLE
Test suite failure on s390x architecture

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#111]
Hello,

The test suite is [failing on the s390x architecture](http://autopkgtest.ubuntu.com/packages/o/ocrmypdf/zesty/s390x), though previously it was passing.  This is a big endian architecture, which might be relevant, looking at the failure.

I understand if this isn't something you're able to fix, but maybe you'll know immediately what to do upon viewing the logs.

Thanks!

**Comment by jbarlow83** [comment]
Well, that's interesting....

test_remove_background: I strongly suspect this is a [leptonica](https://github.com/DanBloomberg/leptonica/blob/v1.73/src/adaptmap.c#L293) issue. Leptonica's latest unreleased version has many fixes compared to v1.73 from a [Coverity scan](https://github.com/DanBloomberg/leptonica/issues/208). This feature was added in ocrmypdf 4.3 and has failed in the same way every time on s390x. I don't think this is worth investigating further until the next release of Leptonica -- maybe that's enough of an excuse to suspend ocrmypdf on s390x for now?

test_oversample[tesseract]: Although the error message appears to be different the problem is likely the same. It so happens that the 4.3.2 and 4.3.3 give a convenient differential diagnosis here. 4.3.2 as a quirk of its Ghostscript output handling bug shows the output from Ghostscript but dumps it to stdout which triggers an error (since one of my general conditions is a clean stdout unless writing output to stdout).

```
            **** Error reading a content stream. The page may be incomplete.
                        Output may be incorrect.
            **** Error: File did not complete the page properly and may be damaged.
                        Output may be incorrect.
```

4.3.3 fixes the output problem, showing us something about what went wrong. To get as far as it did, Ghostscript had to produce a structurally valid PDF with no images (meaning 'xres' is undefined). That this happens in test_oversample[tesseract] but not test_oversample[hocr] narrows this to the tesseract PDF renderer -- but that's as far as I can get without access to intermediate files.

**Comment by spwhitton** [comment]
Thanks for your reply.

Are the intermediate files not included in the artifacts tarball
downloadable from the page I linked?

-- 
Sean Whitton

**Comment by jbarlow83** [comment]
The artifacts tarball only contains a few text files that describe the test configuration. It doesn't have the equivalent of the tests/output folder.

Although tests/output is probably not enough to solve this one. I would need to see the temporary intermediate files. If there is a way to configure what artifacts get captured by Debian CI, I'd like to arrange for the test suite to save temporary intermediate files for any tests that fail. At the moment the test suite is not capable of that. Or if the policy is to always keep intermediate files as artifacts I could arrange that too.

**Comment by spwhitton** [comment]
The spec says:

    If tests want to create artifacts which are useful to attach to test
    results, such as additional log files or screenshots, they can put them
    into the directory specified by the ``$AUTOPKGTEST_ARTIFACTS``
    environment variable.

If you could implement this in git, we could run the tests on one of Debian's s390x machines -- you don't need to make a release of ocrmypdf in order for us to do that.

**Comment by jbarlow83** [comment]
Before I worry about getting intermediate files, let's see if we can get the build system to pick up the ordinary output files. I'm interested in this in part because maybe they will answer the question anyway, and partly because there might be limitations on the artifacts the CI server is willing to pick up - "log files or screenshots" sounds a little like it may be implying a file size limit.

Can you change your script so that the test suite is run with this environment variable exported:
```bash
OCRMYPDF_TEST_OUTPUT=$AUTOPKGTEST_ARTIFACTS
```

There's nothing to pull. This environment variable already works.

**Comment by spwhitton** [comment]
I've asked a friend with access to the relevant machine to just go ahead
and run the test suite in the way that you suggest.  Will report back.

Rather than try to determine the limitations of Ubuntu's CI server by
making uploads to Debian, I'm trying to get in touch with the Ubuntu
admins to see whether autopkgtest.ubuntu.com imposes a size limit on the
artifacts tarball.

-- 
Sean Whitton

**Comment by spwhitton** [comment]
I've e-mailed you the contents of OCRMYPDF_TEST_OUTPUT.

With regard to the artifacts tarball, I've been told that there is no limitation on its size, but we are asked that it be kept small -- it would be bad if it were multiple megabytes in size every single time the tests are run.

I hope this info helps you figure it out!  Thanks again!

**Comment by jbarlow83** [comment]
Issue migrated to Debian developers.

**Comment by spwhitton** [comment]
For reference: https://bugs.debian.org/849094
