### ISSUE TITLE
future  roadmap

### ISSUE THREAD

**Issue by wanghaisheng** [jbarlow83/OCRmyPDF#112]
is there any specific roadmap about which function will be enhanced or added ？
can we make the ocr part Plug-and-Play，what if we can combine  google cloud ocr api  ? right now it seems we can use hocr conversion tools to transform google result into hocr format

**Comment by jbarlow83** [comment]
Roadmap:

* Deal with non-reentrancy of "import ocrmypdf"
* Deal with non-reentrancy of "import ruffus"
* Add a high level API for people who prefer to write Python scripts to drive OCR jobs
* Add a low level API that allows people to implement custom pipelines or processing steps
* Improve hocr to PDF conversion

I'm working on the reentrancy issues at the moment.

I have attempted a few different improvements that were all stopped by the fact that Python has no robust PDF library that meets my needs. I have considered solving that problem myself. It's possible that one of those steps might get halted for a PDF library improvement detour.

If you have a look at pipeline.svg you can get an overview of how ocrmypdf breaks a PDF into images and reconstructs it. It's fairly easy to hook in a new processing step if you change the source, it's just not doable from an external program at the moment.

It would not be too difficult to implement Google's Cloud OCR as an alternate OCR provider. You would insert a function that executes in parallel to `tesseract_ocr_and_render_pdf` in __main__.py. I have tried this before with Abbyy's OCR engine, but it never kept it because its results aren't that great in my opinion. Contributions welcome.

It seems that Google's API does not help with creating PDFs. Are you saying there are already tools to convert Google OCR JSON to HOCR?

**Comment by wanghaisheng** [comment]
no  i have not found any  tools to convert Google OCR JSON to HOCR yet.  i  am participating in Hocr 2.0 specification now .
mozilla has a wonderful pdf library

**Comment by jbarlow83** [comment]
Mozilla's pdf.js is great but it cannot create new PDFs, only view existing ones. Also it's a Javascript library.

**Comment by amitdo** [comment]
(c / python)
https://github.com/dinosauria123/gcv2hocr

**Comment by jbarlow83** [comment]
@amitdo Thanks, good to know that is available.

**Comment by wanghaisheng** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/NeuralNetsInTesseract4.00
tesseract have released NeuralNetsInTesseract4.00 .will ocrmypdf support this one ?
@jbarlow83

**Comment by jbarlow83** [comment]
It already supports tesseract 4 including LSTM.

**Comment by wanghaisheng** [comment]
@jbarlow83   got
