### ISSUE TITLE
Output PDFs have decreased quality

### ISSUE THREAD

**Issue by Wikinaut** [jbarlow83/OCRmyPDF#125]
@jbarlow83 

When comparing the visual quality of PDF files output from OCRmyPDF, I noticed a degradation in almost any cases I tried.

It looks, as if somewhere in the processing chain either a **lossy** compression or some other image-quality-decreasing step is performed.

Please can you check this in your workflow.

I always prefer that the PDF output quality is *exactly* the same as the input quality. 

See also https://github.com/tesseract-ocr/tesseract/issues/660 .

**Comment by Wikinaut** [comment]
(I dedicate myself to help to fix the issues. If I can.)

**Comment by Wikinaut** [comment]
Original (input)

![20170117-03 03 34_auswahl](https://cloud.githubusercontent.com/assets/1151915/22005229/c33cdb08-dc61-11e6-92af-6d9b2bdce3a5.png)

Output pdf after OCRmyPDF

![20170117-03 03 58_auswahl](https://cloud.githubusercontent.com/assets/1151915/22005233/c7b979de-dc61-11e6-808d-65925f1529a0.png)

**Comment by jbarlow83** [comment]
If you are using `--force-ocr` (`-f`) (like in your previous example) then there will be some degradation because this mode rasterizes the PDF to one image per page and builds a new PDF from the images. If the image was originally stored as lossless it will be saved as lossless again (possibly losing some data), or if JPEG it will be reconstructed as a new JPEG (definitely lossy).

The normal behavior is to error out on pages that contain text rather than presume what the user wants. Or if `--skip-text` is given, do not perform OCR on any page that has text already and copy the page to the output without modification. Is the intention with these files to redo OCR done by older Tesseract?

**Comment by Wikinaut** [comment]
I just want to point out: do not use lossy compression when recompressing. Even when the input was jpeg (lossy), do not use again jpeg. This step will worsen the image quality.

The issue was discussed in the past many times.

**Comment by Wikinaut** [comment]
Or: use the original image, as discussed in https://github.com/tesseract-ocr/tesseract/issues/660 .

**Comment by Wikinaut** [comment]
Just for the record:

`$ocrmypdf --help`

explains this

```
OCRmyPDF attempts to keep the output file at about the same size.  If a file
contains losslessly compressed images, and output file will be losslessly
compressed as well.
```

**Comment by jbarlow83** [comment]
Lossy compression on output is only enabled when lossy compression was used on the input and it is not possible to transfer the input image to the output (because of `--force-ocr` or preprocessing that alters the image anyway).

JPEG recompression is certainly not ideal but keeping file sizes similar is quite important for my users and clients.

**Comment by Wikinaut** [comment]
@jbarlow83 I understand that some people don't like big files, however, bits are cheap today. For those poor people like me who are interested and working in the archiving business, quality matters.

So we both should come to the conclusion, that both 

1. compact (mixed mode output) files, and/or
1. highest available output image quality (= bitwise-exactly same as input quality, but not a single introduced artefact) of these output files *should* be user-selectable. This is why I am now so very interested in the recent discussions, and triggered them, and of course in solutions. I will help to find them.

This is also, why I installed the whole toolchain (ghostscript, unpaper, tesseract, ocrmypdf) in their latest available versions ("bleeding edge"), and why I wish to work together with you to find a solution for 1. and 2.

**Comment by jbarlow83** [comment]
Since you explained your workflow in the tesseract forums I now understand why you're using `--force-ocr`. I will look into adding an option to discard any existing OCR text for the purpose of redoing OCR. With that in place I can transfer input PDF pages to output grafting on the invisible text layer.

`--force-ocr` needs to stay in place because it has a different use case. It's useful as a big hammer to normalize weird PDFs.

**Comment by Wikinaut** [comment]
Yes, you've got it.

**Comment by Wikinaut** [comment]
Please let me know, if you can "help" me (passing through the original image/original image quality). Until then, I close this issue so that everyone can concentrate on other issues.

**Comment by jbarlow83** [comment]
Can and will, but it may take a few weeks.

**Comment by sojusnik** [comment]
@Wikinaut

I'm having the same issue as you and wonder if you have found a way to preserve the original image quality when doing ´force-ocr`? Searching through the issues here and applying `--optimize 0` or `--output-type pdf` didn't help.
