### ISSUE TITLE
include source/target pdf in error/info output

### ISSUE THREAD

**Issue by maxandersen** [jbarlow83/OCRmyPDF#136]
Any chance errors/logs could state what file is being OCR'ed so it is easy to see what file is the issue ? 

Here is the current ouptut for a bunch of pdf files:

```
find . -name "*.pdf" -exec docker run -t -i -v $(pwd):/home/docker jbarlow83/ocrmypdf-polyglot  --deskew -l fra+deu+eng+dan '{}' '{}' \;
   INFO - Output file is a PDF/A-2B (as expected)
   INFO - Output file is a PDF/A-2B (as expected)
WARNING -    3: [tesseract] lots of diacritics - possibly poor OCR
WARNING -    7: [tesseract]  took too long to OCR - skipping
   INFO - Output file is a PDF/A-2B (as expected)
   INFO - Output file is a PDF/A-2B (as expected)
   INFO - Output file is a PDF/A-2B (as expected)
WARNING -    1: [tesseract] unsure about page orientation
  ERROR -    1: [tesseract] Error in boxClipToRectangle: box outside rectangle
  ERROR -    1: [tesseract] Error in pixScanForForeground: invalid box
   INFO - Output file is a PDF/A-2B (as expected)
   INFO - Output file is a PDF/A-2B (as expected)
```

No idea which files or pages the WARNING's or ERROR's are about....

**Comment by jbarlow83** [comment]
With GNU `find`,

```
find -printf '%p' -exec docker ....
```

will prefix every line with the responsible file.

`parallel --tag` is an alternative for BSDs/macOS that have a stripped down version of `find`. `parallel -k --tag` will sort the output by file (but delay the output until each job is done) which may be convenient.

 I will update the documentation to include more examples.

Regarding those errors:

* `WARNING -    3: ...` indicates page 3 of a file, whose name should now be much easier to find, was responsible. You could set ``--tesseract-timeout 300`` to allow 300 seconds instead of the default 180 to allow more time.

* The "Error in boxClip..." message seems to be mostly harmless. See https://github.com/tesseract-ocr/tesseract/issues/427.

Aside: you can omit the `-t -i` from `docker run`; that tells docker to create an interactive terminal which the find command doesn't need.

**Comment by maxandersen** [comment]
I know you can tweak gnu find to do that, but for OSX and Windows users this just get tedious. Just a suggestion.
