### ISSUE TITLE
recent python-ruffus error

### ISSUE THREAD

**Issue by sagittarius06** [jbarlow83/OCRmyPDF#140]
On Archlinux, ocrmypdf recently stops working.

$ ocrmypdf -l fra scan0196.pdf out.pdf
  ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pipeline.py", line 497, in ocr_tesseract_hocr
    log=log
  File "/usr/lib/python3.6/site-packages/ocrmypdf/exec/tesseract.py", line 232, in generate_hocr
    universal_newlines=True, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 836, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1533, in _communicate
    self.stdout.errors)
  File "/usr/lib/python3.6/subprocess.py", line 735, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 155: invalid start byte

**Comment by jbarlow83** [comment]
It seems that tesseract printed an invalid character to its standard
output. Maybe this is a tesseract 3.05 issue as that was just released.
Please send the file if possible.

**Comment by sagittarius06** [comment]
Here is an example that fails scanned on my HP 8600
[scan0197.pdf](https://github.com/jbarlow83/OCRmyPDF/files/819686/scan0197.pdf)

**Comment by sagittarius06** [comment]
Issue resolved with latest packages updated :D

**Comment by rennefJ** [comment]
I am seeing exactly the same issue. I am using the homebrew version on macOS 10.13.1.
'UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 155: invalid start byte'
I haven't used it in some time, so I am not sure since when it does not work anymore.
ocrmypdf version 5.4.3 and tesseract version is 3.05.01
If it is really the tesseract data files, I am using the most recent ones for the 3.05 release.

Any suggitions on how to fix it are appriciated.

**Comment by jbarlow83** [comment]
Do you have a file and command line that demonstrates the issue? Or do all
files and arguments seem to fail?

Can you run tesseract on an image on its own?

**Comment by rennefJ** [comment]
Thank you for asking these questions. 
I was able to solve the issue. 
The error only occurred when selecting German as language. 
It turns out I was using the German tessdata file for the 4.0 branch instead of the 3.05 branch. 
This was just my mistake since I don‘t know how to download the German language file automatically I always download it manually.

**Comment by jbarlow83** [comment]
@rennefJ I added a change to v5.4.4 that should print a helpful error instead of suppressing the error from tesseract. If you can test it again with v5.4.4 and let know what happens. I was not able to replicate it exactly by replacing 3.05 tessdata with 4.00.

**Comment by rennefJ** [comment]
@jbarlow83  I updated to v5.4.4 and ran with the wrong tessdata file again. 
What happens is that is puts out 100k lines of text on the console. The first line is the following error message: 
>   ERROR -    1: [tesseract] command line output was not utf-8. This usually means Tesseract's language packs do not match the installed version of Tesseract.

The rest is INFO level messages. I have attached the console output as a compressed text file.
[ocymypdf_testlog.txt.zip](https://github.com/jbarlow83/OCRmyPDF/files/1526240/ocymypdf_testlog.txt.zip)
In the end it creates the output pdf, which it did not do before, and writes:
>   INFO - Output file is a PDF/A-2B (as expected)

The first line is a useful error message, but it could get drowned in all the other output created.
