### ISSUE TITLE
(At least) jbarlow83/ocrmypdf-tess4 docker-image doesn't build automatically

### ISSUE THREAD

**Issue by 17Halbe** [jbarlow83/OCRmyPDF#155]
Somehow the automated build for the docker image ( jbarlow83/ocrmypdf-tess4) didn't kick in again. Can you please build it manually? Thanks a lot!

**Comment by jbarlow83** [comment]
I tried a change to the Docker hub settings. It is currently rebuilding the latest, and hopefully it should work automatically now.

**Comment by jbarlow83** [comment]
My Dockerfile was pulling ocrmypdf from PyPI so sometimes Docker Hub would race with Travis CI. Normally Docker Hub takes much longer to build, but sometimes it wins the race causing a rebuild of the previous version. Changed Travis to explicitly trigger Docker Hub. This fixed jbarlow83/ocrmypdf and -polyglot but not -tess4.

Docker Hub has an undocumented feature that linked repositories are ignored unless they are also referenced in the `FROM` line in a Dockerfile. ocrmypdf-tess4 is built directly from Ubuntu since reinstalling Tesseract from PPAs is a pain, so Docker Hub ignores the FROM line. We now explicitly trigger this repo as well from .travis.yml. Now we try again to see what new surprises await.

**Comment by 17Halbe** [comment]
Thanks for the explanation! 
I'll keep my eyes peeled. Let's hope for the best! 

...von unnerwegs...

**Comment by jbarlow83** [comment]
fixed
