### ISSUE TITLE
pdfa.py license problem

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#187]
Hello,

pdfa.py contains postscript derived from the file `lib/PDFA_def.ps` in the source of GhostScript.  This file is licensed under the GPL, version 3 or later.

IANAL but it's not clear to me that OCRmyPDF can have the Expat license because the source code of that part of pdfa.py would always need to be distributed with any binaries.  And it's not clera someone would ever want OCRmyPDF without that file.

This isn't a problem for Debian because I can indicate that the file has GPL content, but I thought you'd want to know.

**Comment by jbarlow83** [comment]
The Ghostscript project is Affero GPL.

OCRmyPDF can work with that file in ``--output-type pdf`` mode ("don't produce a PDF/A") so it is independent and could be made to work in the absence of that file, or actually, of Ghostscript.

I suppose mark it as possible GPL content. 

I'm not sure it would be copyrightable because it seems to be a nearly trivial work, analogous to a list of ingredients. It populates a few dictionaries with specified records and contains a single condition that amounts to "if color is gray set N = 1, else set N = 3".

**Comment by spwhitton** [comment]
If you look in the LICENSE file of upstream GhostScript, you will find
that lib/PDFA_def.ps is GPL, not AGPL.

That's for the info about working without GhostScript.

I've no insights/knowledge whether it's copyrightable or not, I'm
afraid.

-- 
Sean Whitton

**Comment by jbarlow83** [comment]
Will likely resolve by changing the whole project to GPL since there are other benefits to that.

**Comment by spwhitton** [comment]
Cool!  Bear in mind that many of the test resources will remain under the old license unless you contact all the submitters and have them relicense.

**Comment by jbarlow83** [comment]
Fixed for v6
