### ISSUE TITLE
Option to generate PDF/A-1b

### ISSUE THREAD

**Issue by Aleciano** [jbarlow83/OCRmyPDF#192]
First, I would like to thank you for this awesome tool!

I have a particular scenario in which we need PDF files with the PDF / A-1b format. Ghostscript can generate PDF / A-1b and PDF / A-2b. Is there a way to include such an option in ocrmypdf? Lately , I'm processing the ocrmypdf generated PDF file with ghostscript (gs command) to convert in PDF/A-1b.

**Comment by jbarlow83** [comment]
Sure, I can add this for the next release.

Based on my change logs I think I changed from 1b to 2b because a tool I used to check compliance didn't work properly on 1b. However, I ended up removing the tool because it didn't really work with 2b either :).

You can try changing it yourself by changing `ocrmypdf/exec/ghostscript.py` around line 142
```
        "-dPDFA=2",
```
Just change the `2` to a `1` and see if anything explodes.

**Comment by Aleciano** [comment]
Hum, thanks. I'm working on that and waiting the next release!

**Comment by jbarlow83** [comment]
Added for v5.4
