### ISSUE TITLE
Does it work on Windows\Xampp ? - or RasPi?

### ISSUE THREAD

**Issue by 4044ever** [jbarlow83/OCRmyPDF#204]
Does it run on Windows / Xampp ?

Or if that's not possible, how about Raspberry Pi?

**Comment by jbarlow83** [comment]
Windows is not supported. Native Windows would be doable but it's the sort
of thing I want someone else do in a PR or sponsor financially since I
personally have no need for it.

Re Xampp - See documentation for general notes about deployment on a
network.

Raspberry Pi should work but would be slow due to lack of processor power,
RAM, and temporary storage.

**Comment by tuxflo** [comment]
Maybe the 'Windows Subsystem for Linux' (Win 10) could be an option for you.

**Comment by jbarlow83** [comment]
Windows Subsystem for Linux and then follow the Ubuntu 14.04 installation instructions and you should be pretty much there. The Docker images are also an option for Windows.

**Comment by 4044ever** [comment]
It was just an idea. I would more likely use a dedicated barebone PC type. Either a small PC box (with Linux) or a Whatever Pi variant with more RAM (many come with 2Gb RAM). What would be considered as 'good hardware'?

**Comment by jbarlow83** [comment]
Very much depends what you're trying to do. I've done some large OCR jobs on AWS EC2 that take hours on their high end Xeon servers. For OCR, no hardware is good enough yet.

A RaspPi with 2GB would probably be enough for a little paperless office setup, although you might have a long waiting for pages to finish (I would guess 100-300s/page), and it might choke on large documents due to inadequate temporary storage.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
