### ISSUE TITLE
ocr file again without rasterizing

### ISSUE THREAD

**Issue by fritz-hh** [jbarlow83/OCRmyPDF#207]
Hi!

Thank for the great work you did in bringing ocrmypdf to this level of quality :-)

I have several files for which I had set the lan option to the wrong language (resulting to a bad ocr result)
I would like to ocr it again but I only have the output of ocrmypdf from the previous run.

My question: Is it possible to ocr it again (i.e. discarding the text detected in the previous run), but without rasterizing the image (but using the original scanned images instead, that should still be in the ocred files)?
The reason I would like to do that, is that I would like to keep the image quality and file size as it was originally.

Thanks for your help :-)

**Comment by jbarlow83** [comment]
Good to hear from you again and thanks.

If you have a pure bag-of-images PDF you can use `pdfimages -j -png` (from memory) to extract the original images and then use `img2pdf` to rebuild the PDF. If the PDF is more complex than that (multiple images per page, masks, etc.) then this process won't work. It also loses any page rotation and cropping in the process; the fact that it only works in this special case is the reason why I haven't implemented it.
 
I really wanted this feature myself, done properly so that it works on all PDFs, which means stripping the hidden text out of the content streams. That's not doable with PyPDF2 – maybe possibly with abuse of its private API, but I just don't trust it has so many open bugs. I'm considering moving to PyMuPDF which means changing ocrmypdf to GPL or writing C++ bindings for qpdf, rather than adding new features that depend heavily on a library I don't trust.

**Comment by fritz-hh** [comment]
Thank you for this detailed answer. I will use this work around till the feature is availabe in ocrmypdf (I woud also like to have it but there is no urgency from my point of view).
I would propose to let this ticket open, so get notification if/when it is natively supported by ocrmypdf.

**Comment by Catscratch** [comment]
Ok, thanks! Nice work.

Ticket can be closed.

**Comment by Jmuccigr** [comment]
@jbarlow83, is there a reliable way to do this?:

> stripping the hidden text out of the content streams

**Comment by jbarlow83** [comment]
@Jmuccigr 

I believe so. By convention OCR text is just text rendered with the text stroke/fill settings set to none (``3 Tr`` in the content stream) so it's just a matter of parsing the content stream and checking for these conditions.

The complications (and the reason it's not implemented yet):

1. You can't remove text if the position of some other object is described relative to that text (at least not without getting this information out of the font, and PDF supports several types of font). In practice it would be pretty rare to mix the two. (Usually if a PDF has OCR text and printing text, the printing text is a watermark or comment added after OCR.)

1. Some OCR programs don't follow the convention. hocrtransform.py in particular, on which a lot of open source OCR programs including ocrmypdf are based, incorrectly rendered *visible* text and draws an image on top. You can delete the image and see the text. You also can't just intersect the bounding boxes because there can be masking and transparency. Here I plan to add a heuristic that checks if characters are being horizontally scaled, as a clue that hocrtransform.py was used, and then rasterize with suspected OCR text removed and see if there's a difference. (That should get everything except PDFs made for print production, where overprinting can be deliberate and visually different, I don't think too many people care about this.)

1. PyPDF2 is buggy, not maintained and I'm sure it will find ways to fail if asked to do the above.

**Comment by Jmuccigr** [comment]
Thanks, @jbarlow83. Really the only place where this is an issue for me is with jbig2-encoded files, for which pdfimages will convert the format and I can't get it back. Instead I use ccit.

**Comment by jbarlow83** [comment]
@Jmuccigr @fritz-hh This feature was added in v7.3 except... it won't work with ocrmypdf v2.x or earlier at the moment. See my previous comment above for why hocrtransform.py didn't mark OCR text correctly.
