### ISSUE TITLE
Crazy feature request: sort out, vectorize, and reuse fonts

### ISSUE THREAD

**Issue by Artoria2e5** [jbarlow83/OCRmyPDF#212]
A few years ago Adobe Acrobat had a feature called "[ClearScan](https://blogs.adobe.com/acrolaw/2009/05/better_pdf_ocr_clearscan_is_smal/)" that traces OCR'ed glyphs into embedded fonts that are scalable. Those glyphs replace the original text, making the PDF smaller in size.

Since OCRmyPDF is able to know accurately where each glyph is, it might make sense to go beyond that and cut glyphs into groups of images that can be sorted into "fonts" by similarity. There's already an open source prior work called [smoothscan](https://github.com/ncraun/smoothscan/) around that uses JBig2 for the glyph-glyph similarity work, but it does not have OCR support. It's also… not that good at using `potrace` from the [looks](https://softwarerecs.stackexchange.com/a/32060) of it..

(Yeah, I am opening up a crazy floodgate of a ton of dependencies for a non-archival feature request.)

**Comment by jbarlow83** [comment]
Well, yes, this would be cool but I don't think it will happen. I'd welcome the feature if someone implemented it of course.

Tesseract doesn't annotate its output with the suspected font. The other way to do it would be to create a font that used ligatures or glyph variants to deal with multiple fonts on the same page, but font encoding is tricky (it needs to look right on every platform) and I don't know much about it. Personally I am concerned about the [6-8 substitution problem that can occur](https://www.theverge.com/2013/8/6/4594482/xerox-copiers-randomly-replacing-numbers-in-documents) with lossy optimization.

I do want to add JBIG2 transcoding at some point (via jbig2enc) which would improve monochrome compression by a similar amount to ClearScan.

**Comment by Artoria2e5** [comment]
OCRmyPDF should be able to avoid the 6/8 problem better than smoothscan does because it actually knows what each character is from tesseract. It also doesn't require tesseract to annotate its output with fonts -- OCRmyPDF only need to have character identifications to get a clean set of images of the same character to run JBig2's classifier on. The font guesses are merely based on something akin to "this character has those three kinds of looks, so let's assign them to separate fonts"-type thinking.

**Comment by jbarlow83** [comment]
I do think it would be neat. Notes I made in no particular order:

* I tried to get smoothscan working but the 0.1 release is 5 years old and only handles 1bpp images. Not maintained. Not much to go with here. GPL3+ so pulling code into OCRmyPDF is not an option unless I change the license (which is definitely on the table). Has a bunch of dependencies I'd prefer to not involve and that duplicate libraries I use (libharu, fontforge).

* It might be possible to add an improved smoothscan to the end of the image processing pipeline, idea being to clean up images before re-rasterizing and sending them for OCR. 

* smoothscan or an improvement to it would need to deal with Tesseract at the API level to really exploit it.

* ClearScan is really a questionable thing to use in anything archival because it's irreversible. You can redo OCR if the input image is preserved, but you can't redo a ClearScan gone wrong. There's an irreversible decision to treat a clump of bits in the input image as a certain glyph, whether that decision is informed by OCR or not. OCR is basically heuristic and it makes sense to keep the original input to a heuristic around, to benefit from later improvements.

* The font side is difficult. Have a look at this [this issue](https://github.com/tesseract-ocr/tesseract/issues/712) I reported and solved in Tesseract related to how they encoded the font in PDFs – just to get a feel for the effort involved, and that's dealing with an invisible font not one that renders differently on different computers.

* Expensive feature to add.
