### ISSUE TITLE
Best option for create French PDF/A

### ISSUE THREAD

**Issue by guldil** [jbarlow83/OCRmyPDF#215]
Hello,

How can I create a PDF / A file with French text?

I'm a bit lost with arguments, look like some of them are incompatible (hocr on latin language, no pdfa in tesseract).

Thanks

Guldil

**Comment by jbarlow83** [comment]
Just use ocrmypdf -l fra and then whatever arguments you like.

The message about Latin means the Latin alphabet, which includes French.
French is fine with the hocr renderer. However the PDF renderer in
tesseract 3.05 is much better so use that version for best quality.


On Feb 5, 2018 23:59, "guldil" <notifications@github.com> wrote:

Hello,

Can i have create PDF/A with OCR on french language ?

I'm a bit lost with arguments, look like some of them are incompatible
(hocr on latin language, no pdfa in tesseract).

Thanks

Guldil

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jbarlow83/OCRmyPDF/issues/215>, or mute the thread

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
