### ISSUE TITLE
How do i Increase the Performance

### ISSUE THREAD

**Issue by kkduke** [jbarlow83/OCRmyPDF#220]
Hi,
I will soon have the task of making about 5000 PDF files searchable. In my current tests, it takes about 20 -30 minutes to convert a 500-page document with ocrmypdf. These are typical incoming invoices (German). Is this a common time value? What new hardware would offer to speed up the process? A workstation with xenon processor? Or I7, Ryzen? Is a high clock or the number of cores more important?
Many Thanks

**Comment by jbarlow83** [comment]
I offer consultation for large scale projects with ocrmypdf like yours. That is what ultimately funds the development of ocrmypdf. If I understand correctly it sounds like you have a backlog of 5000 PDFs to process and then you'll have incoming invoices at a lower rate. I believe I can help save you money by processing the backlog and then looking at the incoming invoice rate to develop an appropriate sized solution. It's quite possible that buying dedicated hardware will be a waste of money in this case.

My basic advice is that you should use Tesseract 4 (not 3) on a machine that supports the AVX2 instruction set. Consider the "fast" training data instead of "best". https://github.com/tesseract-ocr/tessdata_fast – if you don't mind trading off accuracy.

I don't have information on what processors perform best. I tend to think that if you have a lot of short documents (less than 10 pages) high clock speed will matter more, and if you have a lot long documents, number of cores will help more, since ocrmypdf handles each page in parallel. That said, Tesseract 4 is still in development I would hesitate to commit to any hardware; it's quite possible the optimal hardware will change.

If you're interested please reach out by email – jim@purplerock.ca

**Comment by cedeling** [comment]
Please advise fastest settings for these requirements:  We convert each pdf (they range in size from 1 page to over 100 pages each) to single page png images and send those to ocrmypdf using parallel. The conversion to png is to avoid errors like "unable to find trailer dictionary while recovering damaged file" and to sanitize potentially dangerous pdfs.  We also need a single png image for every page, so this recipe works well.   Output is a single PDFA and a sidecar .txt page for every page - we use that txt to insert into DB for full text text searches and your ocrmypdf product with Tesseract 4 is outstanding . very close to the quality we were getting with ABBYY and OmniPage - but ABBY is too expensive and Omnipage runs Windows so ocrmypodf is a lifesaver.

As to speed, your 21 Feb 2018 comment above indicates that since I am doing OCR on many single pages a high clock speed is more important than having many cores.  I usually set -j 4 to send 4 at a time, but I get the fastest speed without any -j setting which I assume used all available resources.  We need speed but it must be sustainable hour after hour without frying the machine.

I shall appreciate your advices, and if we must use your consulting services please advise contact details and rates.
