### ISSUE TITLE
Allow encrypted PDF files R3

### ISSUE THREAD

**Issue by Catscratch** [jbarlow83/OCRmyPDF#223]
Hi,

I got a PDF with encryption R = 3.

Is there any reason you excluded these files? When using qpdf directly I got no problems repairing these files or remove encryption (--decrypt).

Can you always remove encryption when using qpdf? Or may it be possible to add a command line parameter to control if encryption should be removed? In my use case I usually don't want to have encryption or security in target pdf/a format.

Thanks.

**Comment by jbarlow83** [comment]
The reason I don't support it is the principle of orthogonality, that is, I write a PDF to OCR PDF program, not a PDF repair/hacking program like qpdf. I don't think I add value by wrapping qpdf's interface.

It sounds like you had a PDF with the user password clear. That means anyone can open the file and read it, but conforming PDF readers are *supposed to* enforce restrictions unless the operator provides the owner password. So I could remove the owner password in this case, but I don't think that's appropriate since the owner password is a very weak form of certificate (I have the owner password, therefore I created this PDF). 

If a PDF has both a user and owner password (even if they are the same) it is not possible for qpdf or any program to remove the password. (Well, there's `pdfcrack` if you want to brute force it.)

**Comment by Catscratch** [comment]
Ah ok. You're right. I got an encrypted PDF with an empty password. So I can view it in any reader I want without problems. 

Would be nice if these PDFs can be processed. Is this ok for you? (I would say, this is not hacking)

If the process skips PDFs with encryption **and** password ... well, that's ok.

**Comment by jbarlow83** [comment]
No, I won't do it. As I mentioned an owner password is a weak form a digital signature on a PDF – it means someone approved of that exact version of a file. I want users to stop and think about what they want to do in this case. 

I did improve the error messages related to PDF encryption.

**Comment by Catscratch** [comment]
Ok, thats legit. I understand your opinion. 

In my case I got a lot of PDFs of friends or family with empty password encryption. Not because they wanted to encrypt, but because a lot of PDF tools and PDF printers do this by default...only god knows why. ;-)

Especially common printers with scanners on top. They often scan to PDF to a sd card and do this strange things with the resulting PDF.

**Comment by jbarlow83** [comment]
Improved message in v5.6.1
