### ISSUE TITLE
Text with background not detected

### ISSUE THREAD

**Issue by sonnysavage** [jbarlow83/OCRmyPDF#289]
I'm having an OCR issue with text that has a background. The text with a background is not being detected by the OCR process. It is not included in the text ouput.

```
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64)

ocrmypdf --version
7.0.4

tesseract --version
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX2
 Found AVX
 Found SSE
```

I'm using these command-line options: `--clean --remove-background --force-ocr --deskew --oversample 600`

One of my documents has text with a yellow background:
![image](https://user-images.githubusercontent.com/5487663/45094061-3b624f80-b0e8-11e8-8f6d-19fe0ea909d1.png)
Output (just image, no text)
![image](https://user-images.githubusercontent.com/5487663/45094350-073b5e80-b0e9-11e8-9549-67fc0600df5d.png)

Another document has text with a gray background:
![image](https://user-images.githubusercontent.com/5487663/45094454-54b7cb80-b0e9-11e8-8a9a-6fb73ac721d7.png)
Output (just image, no text)
![image](https://user-images.githubusercontent.com/5487663/45094480-6f8a4000-b0e9-11e8-8a66-7ccaeee76830.png)

As you can see from my command-line options, I'm using the `--remove-background` option, but it's making no difference here.

It seems to me that it would be best to convert the documents to black and white, not grayscale, and set a threshold that would removed those backgrounds. I don't see a way to do that with OCRmyPDF.

Please help!

Thank you!

**Comment by jbarlow83** [comment]
Clearly this is from some document that you're not comfortable showing me in full but I'll need a bit more information. I'm not sure how to interpret the fact that those images are very pixelated/zoomed in. You're sending me a screenshot, which is significantly compared to the original PDF.

The other thing that confuses me is this looks like a digital font rather than a scanned document - if so, why does it need OCR?

If I run the images you sent through ocrmypdf and make an educated guess at the DPI, the text is identified correctly. The antialiasing in the color image seems to interfere with background removal.

You could encrypt the PDF for me only, following the example here:
https://github.com/jbarlow83/OCRmyPDF/wiki

You could also use Acrobat or another PDF tool to redact sensitive information.

**Comment by jbarlow83** [comment]
From some further experimentation, the fact that you've cropped the images defeats the remove background algorithm. The more pixels it has to establish what the background color is, the more effective it is at removing the background. The images you provided, since they are cropped, have a high proportion of foreground to background pixels - much higher than would be normal for black text on a yellow page.

In general it does not remove, say, small amounts of yellow highlighting. It's attempting to remove the dominant background color from a scanned image (e.g. to clean up yellowed pages).

**Comment by sonnysavage** [comment]
@jbarlow83

Thanks for your responses! 

1. I zoomed in on the text to visually reveal input/output
2. The background is not on the entire page, just parts of the documents, e.g. section headers
3. The documents are prints from medical systems
4. I will see if there's a way I can redact some to share with you

Finally, these are indeed digital documents. We extract data from prints to send to other medical systems. Some systems send PostScript text, others convert fonts to curves, Chrome prints everything as an image, and we also periodically get documents that have a corrupt font embedding.  All of that results in the need to perform OCR on some of them in order to extract the data.

I apologize for the lack of information in my original post. I can see now that there were several things I didn't make clear.

**Comment by jbarlow83** [comment]
Another option is that I could consult. That way I could sign a NDA or other agreement as appropriate to view the documents as they actually exist in your system. I could also provide advice on how to deploy ocrmypdf in your environment, and implement any specific new features you might need. Reach out if you're interested - jim@purplerock.ca.

**Comment by jbarlow83** [comment]
I determined that this is an issue in Tesseract's thresholding. 
https://github.com/tesseract-ocr/tesseract/issues/1990

**Comment by SpencerRP** [comment]
You can probably close this, as https://github.com/tesseract-ocr/tesseract/issues/1990 was closed in May.
