### ISSUE TITLE
ERROR - unable to find trailer dictionary while recovering damaged file

### ISSUE THREAD

**Issue by christmasjumper** [jbarlow83/OCRmyPDF#306]
Hi,

I'm getting the following error recently on MacOS 10.13.6

ERROR - /var/folders/jc/f7tbq6g176d1kx7xnshlsy3r0000gn/T/com.github.ocrmypdf.gqxcthi3/origin.repaired.pdf: unable to find trailer dictionary while recovering damaged file

Any ideas?

**Comment by jbarlow83** [comment]
There's an index of file contents at the end of a PDF called the trailer.
If it missing - usually because the file was truncated - we attempt to
recover it with QPDF. Sometimes recovery is possible, but it will often
fail if other critical data is truncated too. We can only do so much when
your file is missing some fraction of its contents.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
