### ISSUE TITLE
ocrmypdf just exits without doing anything

### ISSUE THREAD

**Issue by NightMachinary** [jbarlow83/OCRmyPDF#329]
**Describe the issue**
ocrmypdf just exits without doing anything. `tesseract` is installed and works for English.

**To Reproduce**

```bash
ocrmypdf ./The\ Little\ Typer\ -\ Daniel\ P\ Friedman.pdf lil.pdf
```

**Example file**
[Link deleted]
- [x] This is the input file
- [x] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

**System:**

- OS: macos
- OCRmyPDF Version: 7.2.1

**Comment by jbarlow83** [comment]
This worked for me without any difficulty, using version 7.4.0 on macos. Unfortunately the release of 7.4.0 is blocked in Homebrew at the moment for reasons beyond my control. You can use `pip install --user ocrmypdf` as an alternative to install the latest version.

(I removed the link you submitted since it may have pointed to a personal server.)

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
