### ISSUE TITLE
OCRmyPDF in CentOS

### ISSUE THREAD

**Issue by marcogianini** [jbarlow83/OCRmyPDF#363]
Hello.

I have installed CentOS 7 x86_64 on my virtual machine and I want to install OCRmyPDF and its dependencies.
But I can not use yum because it does not recognize OCRmyPDF. I did the installation on Ubuntu 18.04 with success and perfect functioning, but in CentOS I'm not having the same luck.

I apologize for the lack of knowledge but does anyone have any documentation on CentOS and installing the OCRmyPDF version?

Thanks for the help.

**Describe the issue**

**To Reproduce**
What command line were you trying to run?
yum install ocrmypdf

**Expected behavior**
A clear and concise description of what you expected to happen. Include screenshots if applicable.

**System:**

- OS: CentOS 7
- OCRmyPDF Version: 8.2.2

**Additional context**

**Comment by jbarlow83** [comment]
I'm the upstream developer for ocrmypdf. Other people package programs like mine and customize it fit into CentOS or other operating systems, and create the scripts that allow `yum install ocrmypdf` to work.

ocrmypdf is not in CentOS 7 because no one had created a package for it at that time. There is also no way to add it, because CentOS 7 is now in maintenance mode and wouldn't accept a new package.

ocrmypdf is available for Fedora and so should get merged into future releases of RHEL and CentOS:
https://src.fedoraproject.org/rpms/ocrmypdf

So you could use Fedora. Maybe there's a way to backport the Fedora RPM into CentOS? Or you could install manually.

**Comment by marcogianini** [comment]
Hi

For this reason that in Ubuntu worked perfectly with Alfresco, bad in CentoOS 7 is a very big difficulty, even installing all the individual packages.
I have the manual installation.
And now my scenario is:
CentOS 7
Tesseract 3.05.01
Leptonica-1.77.0
Unpaper 6.1
QPDF 8.3.0
Ghostscript 9.26
OCRmyPDF 8.2.2
And when I run the command line ocrmypdf it informs that it can not call the library liblept.so.5.

**Comment by jbarlow83** [comment]
You'll need to compile Leptonica and Tesseract >= 4 from source, because ocrmypdf >= 8 requires Tesseract 4.

Tesseract 4 has a CentOS 7 compatible package. It probably includes Leptonica too.
https://github.com/tesseract-ocr/tesseract/wiki

**Comment by marcogianini** [comment]
Thanks i´ll great success.
