### ISSUE TITLE
file junkpixt

### ISSUE THREAD

**Issue by Chris122AT** [jbarlow83/OCRmyPDF#368]
Hello jbarlow83,

thank you so much for your work!

There is following problem, if OCRmyPDF runs via PHP-script (on a Synology NAS):
If the script is searching for freshly OCR'ed text in a PDF by using regex, and if the regex-search includes **AND** matches german umlauts (äöüÄÖÜ) or the german letter sharp S (ß), a file named "junkpixt" (without extension) will create in the workdirectory.

At this point, the PHP-script delets this file if exists, but thats not the clean way ;-)

Best regards
Chris

**Comment by jbarlow83** [comment]
It actually has to do with the `--remove-barcodes` feature, or whatever it is called, and that in turn is a bug/annoying behavior in the third party library that implements this feature. I looked again and I see that my attempted workaround for this problem didn't quite fix it, but I'll have it fixed in the next release.

**Comment by Chris122AT** [comment]
Yes, I'm using the `--remove-barcodes` function in the script!!

Thank you for your response and all the best for this project!

**Comment by jbarlow83** [comment]
Fixed in v8.2.3
