### ISSUE TITLE
Install from Brew,  --redo-ocr still need pdfminer

### ISSUE THREAD

**Issue by oscargong** [jbarlow83/OCRmyPDF#372]
**Describe the issue**

Clean and brand new macOS, install OCRmyPDF from Homebrew.  Using `--redo-ocr` option still need `pdfminer`.

However, in the 8.0.0 release notes:
> It is now possible to use ocrmypdf without pdfminer.six, to support distributions that do not have it or cannot currently use it (e.g. Homebrew). Downstream maintainers should include pdfminer.six if possible.

Anything goes wrong?

**Comment by jbarlow83** [comment]
Homebrew will not accept pdfminer.six because the latest version of pdfminer.six was not released as a tarball as Homebrew requires.

https://github.com/pdfminer/pdfminer.six/issues/208

So there's nothing I can do about this. You can install ocrmypdf using brew to satisfy the non-Python dependencies and then use `pip3 install --user ocrmypdf` to get the latest version including pdfminer.six.
