### ISSUE TITLE
Removing black edges from scanned documents

### ISSUE THREAD

**Issue by githubnavigator** [jbarlow83/OCRmyPDF#374]
Thank you for this very helpful software!

I am looking for a way to remove the black shadows that sometimes get created around the edges of scans. Is there a way to do this, by any chance? I believe unpaper has this functionality, but I experimented with --unpaper-args (tried --size letter and --output single) but haven't been able to make it happen. I am using Ubuntu with OCRmyPDF version 8.1.0. You can see the black borders on some of the pages below. To create the file pictured below I used the following command: 

`ocrmypdf --unpaper-args '--layout single' --clean-final --deskew --optimize 3 --jbig2-lossy --force-ocr pdf-orig.pdf pdf-new.pdf`

![Annotation 2019-03-27 084731](https://user-images.githubusercontent.com/48996626/55090874-170e9600-506d-11e9-868f-5bf286eeb424.jpg)

Thank you!

**Comment by jbarlow83** [comment]
It's fairly difficult to distinguish those marks from meaningful content especially when they're not in direct contact with the edge.

You could try experimenting with unpaper's settings on a single page image -- less tedious than running ocrmypdf on a big-ish issue, specifically the `--blackfilter-scan*` arguments. Use `ocrmypdf -k` to generate some intermediate page images.

**Comment by rbrito** [comment]
@jbarlow83, if the black artifacts of the parts are flushed to the left/right/top/bottom of the page, then a potentially very useful option of OCRmyPDF to pass to unpaper would be an appropriately computed `--pre-wipe` (in the---unfortunately--very common case of pages of almost the same size, but not quite) with, say, "wipe the 10 pixels closest to the border" (or, in the case of dpis being specified, letting the user say "wipe the 1mm closest to each border") would be very cool.

Since OCRmyPDF already has all the dimensions of the images at hand, generating the adequate `--pre-wipe` rectangles with the dimensions appropriate to each individual page is a pain (it could be scripted, but doing that in the image processing stages of unpaper looks like a very helpful feature).

**Comment by jbarlow83** [comment]
I've since added `--unpaper-args` for those who want to send special arguments to unpaper. Unpaper continues to be a pain for integration and packaging due to its long list of dependencies and weak support on Windows. I will probably spin it off as a plugin eventually.

It's basically in ocrmypdf for historical reasons and I think to be really useful, it would need a GUI for the user to fine tune its parameters.

**Comment by rbrito** [comment]
Hi, @jbarlow83,

On Jun 05 2020, jbarlow83 wrote:
> I've since added `--unpaper-args` for those who want to send special
> arguments to unpaper. Unpaper continues to be a pain for integration and
> packaging due to its long list of dependencies and weak support on
> Windows. I will probably spin it off as a plugin eventually.

I can imagine that, having two moderately successful projects that have
problems when running under Windows.

Since you told me about unpaper in particular, I don't know if you are aware
of the existence of a reimplementation of unpaper's algorithms (with some
extra ones) in a python 3 accessible manner in the form of a library:

    https://gitlab.gnome.org/World/OpenPaperwork/libpillowfight

From their README:

,----
| (...)
| Available algorithms
| 
|     Unpaper's algorithms
|         Blackfilter
|         Noisefilter
|         Blurfilter
|         Masks
|         Grayfilter
|         Border
|     Canny edge detection
|     Sobel operator
|     Gaussian blur
|     ACE (Automatic Color Equalization ; Parallelized implementation)
|     SWT (Stroke Width Transformation)
|     Compare: Compare two images (grayscale) and makes the pixels that are different really visible (red).
|     Scan borders: Tries to detect the borders of a page in an image coming from a scanner.
| (...)
| Note regarding Unpaper's algorithms
| 
| Many algorithms in this library are re-implementations of algorithms used by
| Unpaper. To make the API simpler to use (.. and implement), a lot of
| settings have been hard-coded.
| 
| Unpaper applies them in the following order:
| 
|     Blackfilter
|     Noisefilter
|     Blurfilter
|     Masks
|     Grayfilter
|     Border
| 
| I would advise applying automatic color equalization (ACE) first.
| (...)
`----

Since I know how painful it is to fork/exec subprocesses all the time (and
it kills performance), you may be interested in evaluating the library above
(I don't know how mature it is).

In the best of the worlds, it can possibly help with a Pillow interface that
will connect wil everything else and **not** having to write uncompressed
pbm/pgm/pmn files---say, use tiff with RLE/packbits instead for intermediate
files, which should be fast, while saving some space for short-lived files.

For people (like me) that don't have any SSDs in sight (yes, the exchange
rate of BRL to USD is sky-high right now), this small compression saving
temporary storage/HDD bandwidth would also save time (and, for those that
use SSDs, fewer rewrite cycles/longer media durability).

(It is an unfortunate fact that unpaper currently can accept TIFF files as
input, but not as output. :-( )

Substituting forking of external (e.g., unpaper) processeses combined with
the abilityt of saving temp files in a lightly compressed format may have
the potential to cut a few percent (or maybe not so few percent) of the
running time of ocrmypdf (we need to test), but if the results are the same
or equivalent, that would be a win.

If calling/using the library is easy enough/pythonic and in line with the
rest of the program, that's another win. And if it is easier to build and
distribute for Windows users, then, that will be a pain point removed from
your back.

> It's basically in ocrmypdf for historical reasons and I think to be really
> useful, it would need a GUI for the user to fine tune its parameters.

The removal of some pixels and of clusters from unpaper is welcome. Looking
at the history of ocrmypdf, I see that you already use leptonica's deskew
instead of unpaper's.  I don't know if you use any other of leptonica's
features (besides leptonica being used by agl's jbig2 encoder), but if
libpillowfight is suitable for use in place of unpaper, then we may ask for
leptonica's deskew to be implemented there and have (potentially) one fewer
place where another external dependency is needed.

P.S.: This reminds me that I should upload jbig2 to Debian archives...

Hope this helps, if you didn't know about this library that I mentioned.


Regards,

Rogério Brito.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by jbarlow83** [comment]
I did look at libpillowfight a few years ago and it hasn't moved a lot since. It's in Debian now, and has tests, which are both steps forward. It does not have CI/CD for Python binary wheels though, which would make it a pain for many users to install (i.e. compiler required).

Leptonica's deskew is clever and efficient. `--remove-background` is also implemented with Leptonica.

Maybe it would help a little to stream data through unpaper.py, omitting temporary files. If you run out of RAM it will get swapped though.

I believe Debian was waiting for jbig2 patents to expire, and I believe the last one expired in 2017, so they should be able to take jbig2 now.
