### ISSUE TITLE
The output file size is 2.71× larger than the input file

### ISSUE THREAD

**Issue by marians** [jbarlow83/OCRmyPDF#396]
**Describe the issue**

When converting a document I get the following warning:

```nohighlight
   INFO -    1: page is facing ⇧, confidence 13.07 - no change
   INFO - Optimize ratio: 1.00 savings: 0.0%
   INFO - Output file is a PDF/A-2B (as expected)
WARNING - The output file size is 2.71× larger than the input file.
No reason for this increase is known.  Please report this issue.
```

So I thought I'd go and report this issue.

**To Reproduce**

```
brew install tesseract-lang
ocrmypdf --rotate-pages -l deu \
  --sidecar fulltext.txt  \
  input.pdf \
  output.pdf
```

**Example file**

[input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3264990/input.pdf)

- [x] This is the input file
- [x] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

Source of the test document: http://ratsinfo.roesrath.de/ratsinfo/roesrath/Proposal.html?select=2811

**Expected behavior**

n/a

**System:**

- OS: mac OS 10.14.5 (18F132)
- OCRmyPDF Version: 8.3.0

**Comment by jbarlow83** [comment]
File contains a 1-bit CCITT image with an ICC profile which is quite unusual.

pikepdf misidentified the image type, but that turned out to be unrelated but was useful in that it lead to several other issues being explored and fixed.

The real reason is that Ghostscript does the sane thing when confronted with this unusual image format: it promotes it to full RGB. It's not really worth detecting when this happens, but I'll add it as a possible reason for file size growth.

**Comment by SpencerRP** [comment]
Maybe close this?
