### ISSUE TITLE
Creating GUI for this program

### ISSUE THREAD

**Issue by Nokia808** [jbarlow83/OCRmyPDF#399]
Hi. I thing that it is very useful to create GUI for this program to make it convenient to use it.

Best

**Comment by jbarlow83** [comment]
I'm currently working on changes that would make it easier for others to implement a GUI or integrate OCRmyPDF into desktop apps.

Most likely someone else will do this before I get there.

**Comment by Nokia808** [comment]
@jbarlow83 
I'm very thankful for your interest, but I'm afraid that somebody other than you will implement all functionalities of your program. Do you have some one inform you that she/he will create full GUI for your program ?

It is very surprising that interest in PDF is little among Linux developers ! We have very powerful PDF libraries on Linux but we have no advanced PDF editor like Adobe acrobat pro !

I asked developer of PDF Slicer to utilize your program & he mark this as "new feature" but unfortuantly he is not interested in create advanced full options PDF editor - see:
https://github.com/junrrein/pdfslicer/issues/76

If you & developers of QPDF & PDF Slicer unites your efforts we will have soon an advanced PDF editor for Linux. 

Your command line achieved very powerful part (optimize scanned PDF) of adobe acrobat pro functions ....

In fact we have already powerful PDF tool for Linux but unfortuantly it's developer stop it's development .... It need some new features & enhancements to be added + add viewer to it to be something like adobe acrobat pro. It is jPDFTweak - see:
https://sourceforge.net/projects/jpdftweak/
see it's powers at:
http://jpdftweak.sourceforge.net/
what it will happen if some one fork it & complete it's development then you create GUI for your own program ? new jPDFTweak + your program will = adobe acrobat pro

**Comment by jbarlow83** [comment]
No, I haven't asked or had anyone volunteer to create a GUI – and the GUI I had in mind was more like a single dialog box to make it easier to pick the options, not a full PDF editor. It would be great if someone made that someday, but I don't know if I would. 

ocrmypdf fills a need that Acrobat doesn't: it's more of a tool for professionals who have huge batch jobs (thousands) or a OCR-PDF workflow they need to automate as part of a large process. Acrobat doesn't do that at all. pikepdf fills a different need: a better PDF library for Python, mainly because I needed a better PDF library for ocrmypdf. But I'm not trying to compete with Acrobat, I'm doing something different.

GUIs are a lot of work. A full PDF editor like Acrobat is an enormous undertaking - millions and millions of R&D dollars. Now, if you happen to have that kind of money lying around, well, the open source PDF developers may well be interested....

**Comment by Nokia808** [comment]
@jbarlow83 
Thank you very much for your rapid response !

I like just to clarify few points that I feel you miss understand me:

1) I did not mean exactly exactly = to adobe acrobat. We need the core of adobe acrobat pro functionality  which are:

a- annotations tools "add lines, polygons, shapes, underline, cross-line, notes, sticky notes, ......."
b- tool to manipulate PDF: edit document info (auth, date of creation, date of last modification, ......), edit/create outline, edit/add bookmarks, delete page(s), rotate pages, crop, secure reduction, compress, add blank pages, add stamps, add watermarks, combine many PDF files into single one, split PDF file into individual pages or split selected pages range into single output PDF ......
c- tool to optimize scanned PDF

If not possible (or in fact difficult to create single program perform all these in one, then we have:

(a) already existing & performed in Okular which has excellent annotation tool.

(b) not included all in single GUI application yet. The most complete is jPDFTweak. But QPDF is very powerful & can make alternative & for that I asking many to make GUI for it ........ 

(c) is already available as a command line by your program, & for that I asked you to make GUI for it.

So, if you (or other developer) make GUI for OCRmyPDF (an advanced full OCRmyPDF functionality GUI) then we will have 2/3 of acrobat core functionalities (Okular + GUI of OCRmyPDF). The remaining is (b).

I wish you understand me now. 2/3 better than 1/3. So, it is okay if you only create GUI (full options GUI) only for your OCRmyPDF .......

Best.

**Comment by AEgit** [comment]
@Nokia808 
For (b) : Also have a look at PDFSam (https://pdfsam.org/). It is a very simple tool. It definitely does not offer all the features you mention, but a few of them (and it is really easy to use).

Regarding your GUI wish: I don't mean to step into the discussion, but as far as I understand @jbarlow83 is developing ocrmypdf in the spare time. Judging by the contributions at the moment @jbarlow83 appears to be the only (main) developer of ocrmypdf and is definitely not getting paid for this by the users. A GUI would be nice, but sounds like a lot of work. If @jbarlow83 has to set priorities in whether to further develop the actual ocrmypdf tool or just its GUI, I would always support the former. I think it is more important to the users that the tool is stable and offers high performance than it having a fancy GUI.
Having said that - obviously, if there is someone willing to create something like you envisioned (maybe you wish to do it yourself?), that would a nice addition.

**Comment by jbarlow83** [comment]
I am pretty much the only developer; only one other person has offered significant code contributions.

Some companies have sponsored the development of certain features, which is wonderful, but at the same time this is very much a side project.

**Comment by alexanderlanganke** [comment]
I have started working on a very basic GUI using tkinter. This is a hobby project for me. 
First step (working already) is a path picker and a batch job script. This may already be useful to some people not as used to the command line.

As I am a hobby programmer I have no clue how my code would integrate into the main code when it's a bit more mature.
@jbarlow83 -> how would you like me to start here? Currently I am writing a standalone .py that runs tkinter and calls on your API for functionality.

See alexanderlanganke/ocrmypdfgui on github.

I am in the very early stages...

**Comment by jbarlow83** [comment]
I'm happy to link to your work as long I think it may be useful. Although I think it may be too preliminary at this point.

Generally what you've done makes sense. I'd suggesting to add a setup.py that requires ocrmypdf, and GitHub Actions to auto publish it, so that someone can do "pip install ocrmypdf-gui" and get the latest version of the GUI and ocrmypdf.

I'd also suggest creating a plugin for `get_progressbar_class` so that you can inform users of ocrmypdf's progress. (The plugin would replace the console version with updating the GUI.)

If you want to merge into ocrmypdf - I'm always honored that someone values my work enough to contribute to improving it. At the same time, I would become responsible for maintaining it, so I would be much more picky about how it looks and works before I accept it. My preference would be to use one of the GUI libraries uses native OS widgets, or perhaps a browser-based interface, rather than Tkinter which manages to look and feel alien on every OS at once.

**Comment by alexanderlanganke** [comment]
I agree with you on All Points. 

My Plan is to get a working Version 1 that falls Supports your API. This will be done in tkinter because its easy and I have basic experience here.

I have to Look at setup.py and pip publishing.

After all that I can Look at better gui toolkits and then think about a pull request for your Main program.

**Comment by alexanderlanganke** [comment]
I am having trouble understanding how "I'd also suggest creating a plugin for get_progressbar_class so that you can inform users of ocrmypdf's progress. (The plugin would replace the console version with updating the GUI.)" this works.

I have a tkinter progressbar waiting to be update by ocrmypdf and am not quite sure how to get the progress information from the subprocess.

for example:
result = ocrmypdf.ocr(file_path, file_path, clean=True, language="deu+eng", deskew=True) #ocrmypdf is now running
result.get_progressbar_class() -> not defined or "Attribute Error".

I get that I am obviously missing something here. I believe I have to read progress updates from the console/logging?

**Comment by jbarlow83** [comment]
You need to define a `class YourProgressBar`, and `get_progressbar_class` should simply return `return YourProgressBar`, saying this is the class ocrmypdf should use to create an object when it wants a progress bar. Have a look at `extra_plugins/semfree.py` for an example of a NullProgressBar.

`YourProgressBar` should implement certain methods as described in the documentation.

When you call `ocrmypdf.ocr` it runs in the same process as your application, so it's not in a subprocess. If you do move it to a subprocess, YourProgressBar would have to know how to send progress updates to the application.

**Comment by alexanderlanganke** [comment]
I have created a plugin_progressbar.py with a class called ocrmypdf_progressbar_singlefile -> here, for now, i copied your code from nullprogressbar as an example.

I have implemented a hook in the same .py file:

ocrmypdf.hookimpl
def get_progressbar_class():
    return ocrmypdf_progressbar_singlefile

I run the ocrjob as:
ocrmypdf.ocr(file_path, file_path, clean=True, language="deu+eng", deskew=True, plugins="plugin_progressbar.py")

this returns the following error:
<class 'ModuleNotFoundError'>


Am I missing something obvious? Sorry for bothering you with this amateur hour question...

**Comment by jbarlow83** [comment]
plugins= should be a list.

**Comment by alexanderlanganke** [comment]
I have basic functionality up and running:
1. ) GUI Filepicker for Single File or batch directory
2. ) Settings window which uses the signature module to dynamically display your API options (str and bool options right now)
3. Progressbar for batch operations.


I am trying to implement your progressbar hook and am having trouble with this.
My code:
`#!/usr/bin/env python3

from ocrmypdf import hookimpl

class ocrmypdf_progressbar_singlefile:

    def __init__(self, **kwargs):
        print("initialized progressbar_singlefile")


    def __enter__(self):
        print("Entering Progressbar")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print("Exiting Progressbar")
        return False

    def update(self, _arg=None):
        print("Updating")
        return


@hookimpl
def get_progressbar_class():
    print("Hook activated")
    return ocrmypdf_progressbar_singlefile
`

OCRmyPDF no longer displays any progress information in my terminal window so I do seem to have some effect here. But: None of my print() commands are being called. 

If I understand correctly, your code calls my get_progressbar_class() which in turn returns my ocrmypdf_progressbar_singlefile object. This object has methods (taken from NullProgressBar) which ocrmypdf calls during operation. Inside these methods I would then implement my mapping of your progressinformation to the GUI.

Again, am I missing something obvious?
This should be the last main step towards a functional yet non pretty GUI which also enables batch processing for people that can't script themselves. Your help would be much appreciated.

**Comment by jbarlow83** [comment]
You'd need to call `ocrmypdf.ocr(...plugins=path/to/plugin)` for a quick test. Ideally you should setup a setuptools entrypoint in your setup.py that will tell ocrmypdf to register the plugin. See the pluggy framework documentation here: https://docs.pytest.org/en/latest/how-to/writing_plugins.html#pip-installable-plugins

**Comment by alexanderlanganke** [comment]
I am calling like this:
ocr.py
```
import ocrmypdf
ocr = ocrmypdf.ocr(file_path, file_path, **ocrmypdfsettings, plugins=["plugin_progressbar.py"])
```
plugin_progressbar.py is in the same directory as the rest of the project. Tree Output:
/
├── LICENSE
├── pyproject.toml
├── README.md
├── setup.cfg
├── snapcraft.yaml
├── src
│   └── ocrmypdfgui
│       ├── gui.py
│       ├── __init__.py
│       ├── __main__.py
│       ├── ocr.py
│       ├── plugin_progressbar.py
│       └── settings.ini
└── tests




The code I pasted earlier is from plugin_progressbar.py.

Probably unrelated but because you mentioned entry points (setup.cfg):
```
[options]
install_requires =
  ocrmypdf

package_dir =
    = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src

[options.entry_points]
gui_scripts =
    ocrmypdfgui = ocrmypdfgui:main
```

I am aware that this is not a support forum. If you would like me to seek advice on stackoverflow for example then I will look there. I am bothering you since you obviously know your code best and my dificulties lie in interfacing with that code. The online ressources I have read concerning tqdm and plugins unfortunately have not helped me get past this point. Thank you again for your help.

**Comment by jbarlow83** [comment]
I think the call does not work because you need a relative path to plugin_progressbar.py or a module spec (`ocrmypdfgui.plugin_progressbar`) to use that method.

For the entrypoints setup.cfg would need to be something like:

```
[options.entry_points]
gui_scripts =
    ocrmypdfgui = ocrmypdfgui:main
ocrmypdf =
    ocrmypdfgui_progressbar = ocrmypdfgui.plugin_progressbar
```

and then you likely to have run `pip install -e .` again to ensure entry points are re-evaluated. That is, ocrmypdf looks for setuptools entrypoints in the "ocrmypdf" namespace, while GUIs are registered in the "gui_scripts" namespace.

**Comment by alexanderlanganke** [comment]
I finished my setuptools configuration this morning (europe) and pushed v 0.1 to pypi .

When calling ocrmypdf.ocr , Do you need the path to my Plugin Relative to your Module?

I will try to get snap packaging and publishing done so that build automation is complete for most Ubuntu and derivatives users.

**Comment by jbarlow83** [comment]
When you make a setuptools entrypoint, there should be no need to specify the plugin, because ocrmypdf automatically registers all modules that have an setuptools entrypoint. 

`ocrmypdf.ocr(plugins=...` is used to activate a plugin without installing it in the virtual environment, so it's easier for development or for plugins that you don't want to use always.

snap sounds great.

**Comment by alexanderlanganke** [comment]
I will Look at entrypoints for the plugin.

I have a snap that Was built succesfully in the store in devmode. Running it fails due to a module not found error. I guess something is incorrect concerning my Relative path in the snap itself. 
The snap is autobuilt on snapcraft.io and uses my github repository which can build and publish to pypi without error. I am unsure why pypi works but supposedly a module is not found inside the snap..

**Comment by alexanderlanganke** [comment]
https://snapcraft.io/ocrmypdfgui

**Comment by alexanderlanganke** [comment]
The GUI is coming along.
I can now access the plugin and have it printing something on update. So far so good. 
Right now I am baffled as to how I can get variable information out of there. 

My top GUI Class has a variable which I need to modify by the update() method of the plugin.
This variable is not accessible from the plugin itself -> the plugin class does not know what I am referencing.
Normally I would pass the variable into the plugin class and modify it that way.

What is the intended way for me to get update information out of the plugin?

You put it nicely above: YourProgressBar would have to know how to send progress updates to the application.

Do you have any pointers for me?

**Comment by jbarlow83** [comment]
Generally you'd arrange for a callback function. The progress bar class will invoke the callback in its `update()` method, so the only thing it knows is there's some external function to call. 

Here's one approach:

```python

class Progressbar(...):
     callback = None

     @classmethod
     def set_callback(cls, cb):
         cls.callback = cb

     ...
     def update(self, ...):
         self.callback()
        ...

```

Then in your app you'd do:

```python

from progressbar import Progressbar

# then inside ocrmypdfgui.__init__:
    def increment_progress_bar():
        self.batch_progress += 1 
    Progressbar.set_callback(increment_progress_bar)

```

**Comment by alexanderlanganke** [comment]
Thank you, that helped a lot. I believe I now understand that concept.
Replicating your example does not yield runnable code.
I changed it a bit and got it working. Unfortunately increment_progress_bar is now a subelement of the plugin and therefore knows nothing of the variables insidede ocrmypdfgui.__init__

Output:
```
Settings found
Settings Loaded
set_callback
/home/alexander/Downloads/Abwasser2020 - Kopie.pdf
Path:/home/alexander/Downloads/Abwasser2020 - Kopie.pdf

Hook activated
initialized progressbar_singlefile
{'total': 1, 'desc': 'Scanning contents', 'unit': 'page', 'disable': True}
1
Entering Progressbar
Updating
increment_progress_bar
<plugin_progressbar.ocrmypdf_progressbar_singlefile object at 0x7f7411e28670>
1
Exiting Progressbar
<class 'AttributeError'>
```

Code:
```
#this is inside ocrmypdfgui.__init__:
		def increment_progress_bar(self, args):
			print("increment_progress_bar")
			print(self)
			print(args['total'])

			self.singlefile_progress.set(float(args['total']))
			#self.singlefile_progress.set(float(self.singlefile_progress.get())+1)

		ocrmypdf_progressbar_singlefile.set_callback(increment_progress_bar)
```

this is the class implementation of the plugin:
```
class ocrmypdf_progressbar_singlefile:

    def __init__(self, **kwargs):
        callback = None
        print("initialized progressbar_singlefile")
        print(kwargs)
        print(kwargs['total'])
        self.args = kwargs

    @classmethod
    def set_callback(cls, cb):
        print("set_callback")
        cls.callback = cb

    def __enter__(self):
        print("Entering Progressbar")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print("Exiting Progressbar")
        return False

    def update(self, _arg=None):
        print("Updating")
        self.callback(self.args)
        return
```

Naturally ocrmypdfgui.__init__: has a variable called self.singlefile_progress which I can modify without problems outside of the increment_progressbar: function.

If I omit the "self" argument in increment_progressbar: definition, the code  throws a <class 'TypeError'> and never actually calls the function.

Am I passing the wrong "self"?

**Comment by alexanderlanganke** [comment]
Thank you, that helped a lot.
I believe I have that figured out now.

Working on implementing it.

**Comment by alexanderlanganke** [comment]
Started working in the gui_refresh branch. There is a basic idea of a Layout working on that banch. 

Anything you want to see in the first draft?

**Comment by alexanderlanganke** [comment]
I am working on adding support/selection of languages to OCR.

Your API states: 
```
def ocr(  # pylint: disable=unused-argument
    input_file: PathOrIO,
    output_file: PathOrIO,
    *,
    language: Iterable[str] = None,
...
}
```

I am trying to pass a list() of strings to you. Here are my keyword_args:

{'use_threads': False, 'rotate_pages': False, 'remove_background': False, 'deskew': False, 'clean': False, 'clean_final': False, 'remove_vectors': False, 'threshold': False, 'force_ocr': False, 'skip_text': False, 'redo_ocr': False, 'jbig2_lossy': False, 'keep_temporary_files': False, 'progress_bar': False, 'title': '', 'author': '', 'subject': '', 'language': ['deu', 'en']}

I am getting a:
<class 'ValueError'>

How exactly are you expecting the languages to be passed to you? I was expecting a list of strings to be sufficient. Am I wrong?

**Comment by jbarlow83** [comment]
`en` is not a valid language, should be `eng`. List should be fine.

**Comment by alexanderlanganke** [comment]
Fixed that issue.

I now have a GUI that offers all of ocrmypdfs main functions. 

Version 0.5 is available on PIP if you want to take a look.

Feedback is always welcome.

**Comment by digidigital** [comment]
Hi Guys, I missed that you are already working on a GUI so I started to make one myself...

I took a shortcut, skipped the progress bar topic (by adding an "activity indicator") and simply use the GUI to prepare the command that is passed on to subprocess.  

![OCRthyPDF GUI](https://raw.githubusercontent.com/digidigital/OCRthyPDF-Essentials/main/screenshots/1.png)

https://snapcraft.io/ocrthypdf
https://github.com/digidigital/OCRthyPDF-Essentials

**Comment by alexanderlanganke** [comment]
@digidigital Looks great!
I am unfortunately stuck with packaging my GUI into a Snap. Tkinter does not seem to work correctly in snaps..

A feature I use heavily is the ability to bulk OCR entire directory structures. Perhaps you could add that to your GUI?

**Comment by alexanderlanganke** [comment]
My GUI is working and packaged as a snap. You can find it in the snap store as well.

Http://snapcraft.io/ocrmypdfgui

**Comment by alexanderlanganke** [comment]
I have redone the GUI using GTK 3.
If you are interested in merging the code in the future (running it could be a commandline argument for ocrmypdf for example), let us talk about how I can make the code fit into the project.

My GUI is almost finished. I would like to change the color of a button and need to work on the implementation of threading, so that I can stop the running OCR from the GUI.

**Comment by rugk** [comment]
As a non-Ubuntu user I am [glad to see the OCRmyPDFGUI existing](https://github.com/alexanderlanganke/ocrmypdfgui/) (to also link to it's source code here), but it's just missing [a flatpak package](https://github.com/alexanderlanganke/ocrmypdfgui/issues/30) yet.
