### ISSUE TITLE
OSError: cannot identify image file

### ISSUE THREAD

**Issue by AEgit** [jbarlow83/OCRmyPDF#400]
**Describe the issue**
I have tried to OCR the linked PDF, but no output is generated. The error message that appears is:
`OSError: cannot identify image file <_io.BytesIO object at 0x7f17ff8c3db0>   `

**To Reproduce**
After cd'ing into working directory, I ran the following command:

```bash
for f in *.pdf; do ocrmypdf -v -l eng --force ./"$f" ./"${f%.pdf}_ocr.pdf"; done                                   
```
(I tried both with and without `--force` option)

**Input file**
https://app.box.com/s/z3kh3n4xx7liyhj1saam8p2p0yby2dru

**Expected behavior**
OCR'ing should be possible. In fact I have OCR'ed this file a while a go (I don't remember whether I used ocrmypdf for that), but results were not good, so I wanted to try it again.

**System:**
- OS: Ubuntu 18.04 (in Windows 10 WSL)
ocrmypdf 8.3.1
tesseract 4.0.0-beta.1
gs 9.26
qpdf 8.0.2

**Comment by jbarlow83** [comment]
The file has images that have multiple compression filters applied which we don't seem to handle when one of them is JPXDecode (aka JPEG2000). I think it's pretty rare that there is any benefit to stacking compression with modern codecs, but it's allowed and some PDF software does it because they can.

Will need to fix in pikepdf:
https://github.com/pikepdf/pikepdf/issues/50

**Comment by AEgit** [comment]
Cheers, thank you for the update. Yes, PDFs that I encounter are sometimes quite weird (it wasn't me who scanned the file).

Off-topic:
A big problem I sometimes face is that a text layer appears to be part of a PDF but it contains just garbage text (e. g. all characters are just question marks). As far as I understand in these cases the fonts have not been stored properly in the PDF. It is a shame that this requires to re-ocr PDFs with the `--force` parameter. I was wondering whether it would be possible to restore the missing fonts in these documents? Do you think that would a worthwhile feature request for ocrmypdf? Or is that out of the scope of the package?

**Comment by jbarlow83** [comment]
The text drawing commands in PDF specify the glyph numbers to draw, and the glyph numbers are specific to the font. We need a mapping table that translates glyph numbers to Unicode code points. For the situation you're describing, there is a font but the mapping table is missing or wrong. The mapping table is optional because sometimes no mapping is sensible.

I do some ugly monkeypatching of pdfminer in src/ocrmypdf/pdfinfo/layout.py to address a few cases where it appeared that there was some kind of stable yet undocumented that encoded the appropriate Unicode characters in an non-standard way. That was mainly for a client that a lot of files malformed in a particular way.

I can sometimes detect corrupt text. You can do is `--redo-ocr` which will warn if there is corrupt text but proceed anyway (I don't want to escalate to `--force-ocr` automatically). The only thing done on discovering corrupt text is suggest `--force-ocr`. 

It could work to extract any suspect fonts, create a new PDF, raster all the font glyphs, OCR the characters individually, and from that, rebuild the Unicode mapping. Fonts can contain wingdings or emoji or icons or partial characters other weird things that OCR isn't necessarily expecting to find, so it would have its limits. Ligatures and diacritics would also be problematic with this method of naively extracting the glyphs since some glyphs are only meant to be used in conjunction with others. Because of the limitations this would probably make most sense as a separate tool that uses  ocrmypdf's API. This would be a big project.

**Comment by AEgit** [comment]
Thanks for the heads up and the `--redo-ocr` trick! I shall try that one out.
Ok, the way you explain it, it seems too large of a project for a single developer. Who knows, maybe there is someone else out there, that runs into these issues. It could even be a company, because (as far as I know) a certain version of Windows webservers tends to create this malformatted PDFs (don't ask why that is the case ;)): so there should be quite a few people affected by this.

**Comment by jbarlow83** [comment]
There's already some hacks in place to improve support for Windows-generated PDFs (specifically "pscript5.dll").

**Comment by AEgit** [comment]
Ah, there you go! I might upload one of those PDFs at some stage, so that you can have a look at them. If it is too much effort, to fix the PDFs (as you mentioned above) then you can just close that potential Github issue.

**Comment by jbarlow83** [comment]
Should work now that pikepdf#50 is fixed

**Comment by AEgit** [comment]
Can confirm that his has been fixed in:
ocrmypdf 8.3.2

Thank you very much!
