### ISSUE TITLE
I need a little more help installing a language on Synology docker image

### ISSUE THREAD

**Issue by Bogey** [jbarlow83/OCRmyPDF#403]
I used the polyglot version but recently switched to alpine.
In the docs I read "You may add other languages by creating a new Dockerfile based on the public one", but as I'm using docker on Synology, I'm not clear on how to achieve this.
A little more details on this process would be very helpful.
Thanks

**Comment by jbarlow83** [comment]
From https://ocrmypdf.readthedocs.io/en/latest/docker.html#docker-lang-packs

In an empty folder on your Synology, create a new Dockerfile that begins with the public version and adds new language packs as described above. I don't see a way to do this without SSH.

Then use `docker build -f NewLangsDockerfile -t ocrmypdf-klingon .` to create the image and tag it as `ocrmypdf-klingon`, and `docker run ocrmypdf-klingon` as usual.

Let me know if this is works and I will copy it to the documentation.

As mentioned this is only possible on x86/x64 Synology. Performance may also be poor due to lack of AVX2 instructions.

**Comment by Bogey** [comment]
Yes, that worked perfect! Thank you. :)

Is it possible to tag it as jbarlow83/ocrmypdf-polyglot:latest? I have a Synology package running that has only two flavors I can choose from: jbarlow83/ocrmypdf:latest and jbarlow83/ocrmypdf-polyglot:latest ...

**Comment by jbarlow83** [comment]
You can locally tag it as ocrmypdf-polygot or if you want to push it to your own Docker hub it would be `bogey/ocrmypdf-polyglot`. Or whatever you like to call it.

I am discontinuing ocrmypdf-polyglot and will only offer ocrmypdf and ocrmypdf-alpine.
