### ISSUE TITLE
Cant able to run the ocrmypdf docker command inside a docker container

### ISSUE THREAD

**Issue by AmirthaKrishnan** [jbarlow83/OCRmyPDF#433]
I am inside a docker container trying access another container that is **ocrmypdf**  while running this command error which i get is **/bin/sh: 1: docker: not found** 
docker run --rm -v /tmp/:/tmp -i ocrmypdf --force-ocr --deskew --rotate-pages --remove-background --tesseract-timeout 86400 --sidecar /tmp/tmpc105drim.txt /tmp/tmpzkwae5bb.pdf /tmp/tmp6t5kznyf.pdf

how to run the ocrmypdf command from container to a container ?

**Comment by jbarlow83** [comment]
You can't run a docker container from another container – and that's how docker is designed. You could use the web service API, with your private app in one docker container, sharing an open port to the ocrmypdf web service container. (Of course, the ocrmypdf web service is a toy implementation that's not suitable for production.)

**Comment by AmirthaKrishnan** [comment]
Okay @jbarlow83 can you share the installation steps for installing ocrmypdf in redhat os 
I am facing a lot of dependency issues . 
In ocrmypdf docs, I can see only installation steps for Windows ubuntu debain fedora

**Comment by jbarlow83** [comment]
My thought was to use two Docker containers that have been set up to communicate with each other over HTTP, similar to the typical web server and database Docker container composition.

Unfortunately I don't have an install procedure for RHEL because I don't need it myself, and no one has contributed it. A native installation on the operating system of your choice will perform better than Docker. If this is a commercial project and you want to exploring setting up a contract with me, I'd be happy to discuss the project with you. I could get everything working on RHEL, and otherwise advise about how you could configure and optimize your setup, as I've done for other clients. I could also make improvements to ocrmypdf to help it better meet your needs. 

I hope you can appreciate that I cannot get involved in supporting a specific, commercial deployment when I don't have a business interest in it myself.

**Comment by AmirthaKrishnan** [comment]
Okay, @jbarlow83 Thanks for your update.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
