### ISSUE TITLE
Output file is 5 times biggern, then the input if format is pdf...

### ISSUE THREAD

**Issue by GuidoBo** [jbarlow83/OCRmyPDF#438]
Hi, my input file is usually about 400 to 700 kB, after I perform ocrmypdf on it is around **3 to 5 MB (!)**, if the output format is **pdf**. 

If however I use **pdfa** (with --pdfa-image-compression jpeg) as output format, the new file is only about 20% bigger. 

Is there no way to have a small file *and* use pdf as output (which I need to do)? A switch like "--pdf-image-compression jpeg" does not seem to exist.

Also "--optimize" does not work in my installation. Is there a way I can find out why?

Regards,

GB

**Comment by jbarlow83** [comment]
What version are you using and what platform? How did you install it?

Can you run your command with verbose (`-v 1`) and attach the results?

**Comment by GuidoBo** [comment]
I believe I got it sorted out myself: The problem seems to have been, that **jbig2enc was not installed**. This is what I did to solve the issue:

**Installing JBIG2** it (together w/ other stuff mentioned here: https://ocrmypdf.readthedocs.io/en/latest/jbig2.html) **solved the problem.**

Unfortunately, it appears you cannot install it using apt-get on either **debian** or **ubuntu**; so you need to figure out what's missing on your system by **checking the error messages**, that autogen.sh, configure and make are returning. Stumbling along this rocky install path did the trick for me. If you don't know the libraries it complains about being absent, google them; they all existed for me, but sometimes they are named kindof odd.

Strangely I in the end had to **re-install ocrmypdf**, for it had simply disappeared (I have no clue, why). I did this using **apt-get install ocrmypdf**.

Having jbig2 finally installed, everything worked as expected: filesize of the output file is about the same regardless of whether I use pdfa or pdf as output. Also **the --optimize switch** (-O 1,2,3) works fine now. 

**Thank you so much for your work, jbarlow83!** I am sorry for having bothered you with this in the first place and hope my posting will help others that come across the same issue.

I would like to make a **remark** though: could you maybe emphasize the fact a little more, that jbig2 is very important and should be installed in advance. Also, an **error** message (or at least any message) might be useful when **using the -O switch** while **not having jbig2 installed** and/or when using "--output-format pdf"  without having jbig2?

**Comment by jbarlow83** [comment]
Sorry to hear installation was a difficult process.

Unfortunately I cannot do much about the packaging situation for jbig2enc. It was patented until 2017; they might still be concerned about submarine patents. I found an effort to package jbig2enc from 2017 after the patent expired but the submitter never completed the work.

The fact that jbig2 made this big of a difference likely depends on how the input file was formatted. So it's not necessarily important; it's important for files with a lot of monochrome content.

I think it would be reasonable to issue a warning when we had to forego optimization opportunities because jbig2 was not installed.
