### ISSUE TITLE
Slowness with a certain PDF input file

### ISSUE THREAD

**Issue by aplocher** [jbarlow83/OCRmyPDF#439]
I'm trying to figure out why a 457 page PDF is taking 5 to 6 hours to process (using 6 cores). I've processed several PDFs that are larger (both in file-size, and page-count) than this one, and it handles them in less than 30 minutes typically.

I've increased verbosity and kept the temp files in place to analyze.  

Here is the timeline of temp file creation:

* `origin` and `origin.pdf` files created at 4:07pm
* The next files (`#_rasterize.png`, `#_ocr.png`) started being created exactly 5.5 hours later at 9:37pm
* The entire process was completed 20 minutes later at 9:57pm.

With the increased verbosity, it simply shows this for many hours:

```
DEBUG - ocrmypdf 9.0.3.post6+g68c852a.d20190918
DEBUG - os.symlink(/data/badfile.pdf, /tmp/com.github.ocrmypdf.xkbrm8lp/origin)
DEBUG - os.symlink(/tmp/com.github.ocrmypdf.xkbrm8lp/origin, /tmp/com.github.ocrmypdf.xkbrm8lp/origin.pdf)
```

I do believe this PDF file has problems, and unfortunately it contains sensitive healthcare information so I can't provide it to you. I'm trying to figure out a way to find the problem myself, however, but so far the temp files and the increased verbosity isn't helping me at all. 

* Can you shed some light on what it might be doing after it creates the origin and origin.pdf, but prior to creating the png files? 
* Or what you think the problem might be? 
* Or if there's something else I can do to assess the situation myself (other command line args, or other suggested third party tools)?

This command is what I'm using, which works well with all other files I've thrown at it. It's just this one file unfortunately:

`docker run -a STDOUT -a STDERR --cpus 6 --rm -v C:/temp/pdftest:/data -v C:/temp/tmp:/tmp jbarlow83/ocrmypdf -v 1 -k --redo-ocr /data/badfile.pdf /data/out/badfile-new.pdf 2>&1 | tee -a c:\temp\OCRMYPDF-3.TXT`

Embarrassingly I forgot the `2>&1` when I ran this last night so I don't have the full log output, I'm running it again and can provide the output when it completes in several hours - but I didn't see anything out of the ordinary in the terminal last time.

Just as a small suggestion: it would rock to have the ability to (optionally) include a timestamp in the output 😃 

Thank you!

**Comment by jbarlow83** [comment]
> Can you shed some light on what it might be doing after it creates the origin and origin.pdf, but prior to creating the png files?

Finding the positions of all the images and text in the PDF.

>Or what you think the problem might be?

Likely pdfminer - third party library for exploring text that is required when `--redo-ocr` is issued. I believe this library has some O(n^2) or worse runtimes for certain inputs. If you don't specifically need `--redo-ocr` it will help. 

Unfortunately this library's maintenance has been lacking lately. I already monkeypatch it in various ways.

>Or if there's something else I can do to assess the situation myself (other command line args, or other suggested third party tools)?

You can run `python3 -m pdb -m ocrmypdf -j1 --use-threads ...rest of your command` to run in the Python command line debugger `pdb`, with ocrmypdf set to use only one job, and to use threads instead of processes for easier debugging (not generally advised), and then hit Ctrl+C when you get sufficiently frustrated. This would help me see if we got caught in a deep loop somewhere. It may be just be that it takes a long time to run.

We also could set up a contract and NDA so you can share your files with me and discuss more broadly what you're trying to do. Maybe there's other ways I can help ocrmypdf meet your needs. I'm not pushing anything – just putting it out as a possibility if that makes sense to you.

If you use the ocrmypdf API rather than command line, you can customize the logging.
https://ocrmypdf.readthedocs.io/en/latest/api.html
(Just looking at it now, I realize the documentation is a bit lacking on how exactly to do this.)

**Comment by aplocher** [comment]
@jbarlow83 thank you for your response.  I'm going to go ahead and close this issue.  Unfortunately I was pulled off this project at work (temporarily) and will need to revisit this later.  I appreciate the advice, and I will utilize it when I get back on this.  I will drop a comment to let you know how it goes (when that happens) - but no reason to keep the issue open. 

Thanks again!
