### ISSUE TITLE
rotated pages doesnt work (90 degrees)

### ISSUE THREAD

**Issue by aradhell** [jbarlow83/OCRmyPDF#454]
Hello,

 I am having an issue with rotated pdf files. They are not being fully ocr'd.

edit: I checked the logs and saw

1: page is facing ⇨, confidence 6.94xxxxxx - not enough

if I add --rotate-pages-threshold 1 to the params, it is working perfectly. But how can I decide on the correct threshold? ( because some of the test files returnin 1.xxxx confidence )

**Describe the issue**
When I try to ocr a pdf with mixed rotations it is not working

**To Reproduce**

```bash
ocrmypdf -l eng --rotate-pages --tesseract-timeout 3600 rotatetest-90.pdf output.pdf -v
```

**Example file**
[rotatetest-90.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3840512/rotatetest-90.pdf)

**Expected behavior**

**System:**

- OS: Ubuntu 18
- OCRmyPDF Version: 6.1.2 / 9.1.0

**Comment by jbarlow83** [comment]
Unfortunately, I don't know. I just use Tesseract's default.

Generally speaking people lower the threshold, I've never heard of someone raising it because of false positives (misrotating well oriented pages).

It's very easy to get rotation false positives and there's some documents where humans will argue about the correct orientation too. This is a subjective thing.
