### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by akanksha-niranjan03** [jbarlow83/OCRmyPDF#480]
**Describe the issue**
I am getting an error "pikepdf's extension library failed to import" while using OCRmyPDF.
Also i am getting an error related to qpdf that some DLL file is failed to load.

**Comment by jbarlow83** [comment]
Look at https://github.com/pikepdf/pikepdf/issues/70

**Comment by akanksha-niranjan03** [comment]
thanks...
I solved the previous issue by installing pikepdf 1.7.0 and it is compatible with ocrmypdf 9.1.0 so i replace the latest version of ocrmypdf with 9.1.0.
But i am getting an error again. It says "OSError: cannot load library '<None>': error 0x57". I checked this in the previous issues listed on github and found out that this is some kind of windows error. But i have already installed Windows 10 (64 bit) on my system.
what should i do now to resolve this?

**Comment by jbarlow83** [comment]
Do you have the Visual C++ runtimes installed?

**Comment by jbarlow83** [comment]
There's nothing I can investigate from what you've told me unless you can provide some more detailed information.

What version of Python are you running? Is it 32-bit or 64-bit; you can install 32-bit Python on Windows 64 (unfortunately) and this used to be the default offered by Python.org (unfortunately).

Please run Dependencies https://github.com/lucasg/Dependencies on the pikepdf dll and qpdf dll to see if they are missing anything.

It would make sense to me if pikepdf <1.7.0 worked and pikepdf >=1.7.0 did not, since there was a change to how the libraries were compiled at that time, but there's nothing of the sort since. It makes me thing there's some wrong/odd about your Python configuration if shuffling these versions made a difference.

**Comment by jbarlow83** [comment]
Probably resolved with pikepdf 1.12.0
