### ISSUE TITLE
Unable to compile watcher.py

### ISSUE THREAD

**Issue by Geordon** [jbarlow83/OCRmyPDF#524]
**Describe the bug**
macOS 10.15.4
Python 3.8.2 (managed via pyenv also installed by Homebrew)
Installed OCRmyPDF via Homebrew
Cloned repository locally via GitHub Desktop

manual install of watcher.py failed
>pip3 install -r watcher.txt

See: https://gist.github.com/Geordon/510276d9b87aa776d66bb4c2501218f1

**System**
 - OS: [macOS 10.15.4]
 - OCRmyPDF Version: `ocrmypdf --version
9.6.1`

 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image?
Installed via Homebrew but trying to install watcher.py

**Comment by jbarlow83** [comment]
This issue has something to do with installing the third party dependency `watchdog`.

As the error message suggests, try using upgrading to a newer version of pip and perhaps try making sure your Xcode Command Line Tools are up to date. If you have further problems please report the issue to the watchdog project since the problem you are having concerns that dependency. (You need to be able to do `pip install watchdog`)

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
