### ISSUE TITLE
--skip-text still check if a page contains text ?

### ISSUE THREAD

**Issue by andrew-vdb** [jbarlow83/OCRmyPDF#535]
When running ocrmypdf with --skip-text
it still give this output

```
   INFO -    1: page already has text! - skipping all processing on this page
   INFO -    2: page already has text! - skipping all processing on this page
   INFO -    3: page already has text! - skipping all processing on this page
   INFO -    4: page already has text! - skipping all processing on this page
   INFO -    5: page already has text! - skipping all processing on this page
   INFO -    6: page already has text! - skipping all processing on this page
   INFO -    7: page already has text! - skipping all processing on this page
   INFO -    8: page already has text! - skipping all processing on this page
   INFO -    9: page already has text! - skipping all processing on this page
   INFO -   10: page already has text! - skipping all processing on this page
   INFO - Optimize ratio: 1.01 savings: 0.9%
   INFO - Output file is a PDF/A-2B (as expected)
````

Is there a way to skip checking if a page contains text? Thus it will be faster producing the output maybe?

**Comment by jbarlow83** [comment]
You can use `--pages` if you know in advance that you want to exclude certain pages.

In general no, it wouldn't be faster, because we need information about what images are used too, and can quickly check if there is text at the same time. In theory some of these tests could be skipped for a specific combination of settings, but it would be unsafe. You really, really don't want to apply an OCR layer on top of a text layer in a PDF; all of the text will be duplicated and the document ruined. The whole point of these checks is to make ocrmypdf safe to use on thousands of files without checking them all.

**Comment by andrew-vdb** [comment]
So when we only want to use it to generate pdf/a, it will still try to check if the page contains text?

**Comment by jbarlow83** [comment]
Yes. At the moment there's nothing that requires page analysis to generate PDF/A, but there's also not much reason to optimize this.

But if you just want to generate PDF/A you might well use Ghostscript directly, perhaps with a smaller wrapper script to generate an appropriate .ps file like `ocrmypdf.pdfa.generate_pdfa_ps()` does.

**Comment by andrew-vdb** [comment]
Thats too bad, thanks anyway...
