### ISSUE TITLE
API for reading in and outputting io.BytesIO PDF objects

### ISSUE THREAD

**Issue by alexanderwhatley** [jbarlow83/OCRmyPDF#545]
**Is your feature request related to a problem? Please describe.**
Right now, the API appears to only be able to accept input file and output file paths. What I think would be very useful for many users including myself would to have an API call that accepted a PDF io.BytesIO object in memory, and output a PDF io.BytesIO object that is the processed result. 

**Describe the solution you'd like**
A change or addition to the API that allows what is described above. 

**Additional context**
This would be very useful for certain tasks, such as scanning numerous pdfs in a backend server at once.

**Comment by jbarlow83** [comment]
I agree this should be added but I don't think it will make the cut for my next major release.

Just so you're aware the approach will be to read the whole input stream and save it as a temporary file. Since ocrmypdf does its own parallelism, it needs to random access to the input file from multiple processes, and the approach needs to work on all platforms. Temporary files are the easiest solution. I can't support non-seekable or non-copyable streams. Temporary files are  still quite efficient when multiple processes are accessing them read-only.

For a backend server I really recommend creating a creating a new process per invocation of `ocrmypdf.ocr()`. That will prevent ocrmypdf from taking down your whole backend if something goes wrong ;). `ocrmypdf.ocr()` will grab all available cores unless instructed, and usually does not need to parallelized externally. The only case where it makes sense to parallelize from the outside is when you have lots of files whose average number of pages is significantly less than the number of CPU cores available. In that case, yes, use `jobs=1` or `jobs=2` or maybe `jobs=sqrt(cpu cores)`.

**Comment by karlhayek** [comment]
This would be very useful for my use case as well, where I have a backend server that scans multiple pdfs at the same time.
