### ISSUE TITLE
Is it possible to reduce peak occupancy of `/tmp` when optimize pdf?

### ISSUE THREAD

**Issue by Denis-Oakley** [jbarlow83/OCRmyPDF#560]
**Is your feature request related to a problem? Please describe.**
Maybe it will run better when dealing with large files on small memory devices.

**Describe the solution you'd like**
Reduce peak occupancy of `/tmp` when optimize pdf.

**Additional context**
When small memory devices are processing large files, the optimization process may run out of `/tmp`.
In my case, RAM 8 GB, swap 8GB, `/tmp` 4GB, pdf 200MB, but in the end will run out of `/tmp`.
Is it possible to optimize the optimization algorithm? For example, batch optimization, and directly write the optimized file to disk instead of leaving it in memory. But I don’t know whether it is feasible.

**Comment by jbarlow83** [comment]
As currently written you could disable optimization (`-O0`), manually split the PDF into page groups, and use `python -m ocrmypdf.optimize`, and reassemble. You can also environment variables to redirect `TMPDIR` to e.g. a RAM disk or some other device with more storage, e.g. add a USB stick or SD card. Those are options if you are looking for a quick fix.

It's feasible but I don't know when it would be implemented. I have a feeling the pandemic has made paper capture and OCR utilities more popular, and my work queue longer.

Mostly as notes to self for when I can work on this:

* Refactor `extract_images()` into a function that builds `working_xrefs`, the objects we decided to optimize. Then in `optimize()`, partition the set into smaller groups and loop the group over `extract_images_generic()` through `convert_to_jbig2()`, add a new step to clean up the intermediate files.
* Incidentally, there is no reason to iterate pages while looking for image objects as the algorithm currently does. We could just enumerate the objects, and consider optimizing any image we see that meets our known-format criteria etc.
* We will want group size as an integer multiple of jbig2_page_group_size if that is enabled.
* As a drawback this approach still requires retaining the whole PDF in memory plus memory associated with unoptimized content. Attempts to save intermediates will be frustrated by qpdf object renumbering - objects get renumbered and we don't know what we've optimized if we reopen the file. Could create a private data structure in the PDF with indirect objects pointing to previous optimized objects but that is starting to sound expensive to implement.
* Restructuring to avoid temporary files may not actually reduce memory usage.
* How will this work if page color segmentation is implemented, since optimization currently ignores pages? Segmentation could reasonably be a separate optimization pass, because of the need to test where and how images are used. Could also replace segmented images with Form XObjects that contain the color stack.

**Comment by Denis-Oakley** [comment]
OK, thanks. I'm using `-O 0` now.

I don't understand development, if you think it is unnecessary, please close.

But can it skip optimization when OSError appears?

```
DEBUG - xref = 4086 ext = .png
DEBUG - xref = 4088 ext = .png
DEBUG - xref = 4089 ext = .png
DEBUG - xref = 4090 ext = .png
DEBUG - xref = 4092 ext = .png
DEBUG - xref = 4093 ext = .png
DEBUG - xref = 4095 ext = .png
DEBUG - Optimizable images: JPEGs: 0 PNGs: 826
JPEGs: 0image [00:00, ?image/s]
DEBUG - Optimizable images: JBIG2 groups: (0,)
JBIG2: 0item [00:00, ?item/s]
INFO - Optimize ratio: 1.00 savings: -0.1%
INFO - Image optimization did not improve the file - discarded
ERROR - An exception occurred while executing the pipeline
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 396, in run_pipeline
exec_concurrent(context)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 324, in exec_concurrent
pdf = post_process(pdf, context)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 178, in post_process
return optimize_pdf(pdf_out, context)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 794, in optimize_pdf
optimize(input_file, output_file, context, save_settings)
File "/usr/lib/python3.8/site-packages/ocrmypdf/optimize.py", line 550, in optimize
pike.save(output_file, **save_settings)
OSError: [Errno 28] No space left on device
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 396, in run_pipeline
exec_concurrent(context)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 324, in exec_concurrent
pdf = post_process(pdf, context)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 178, in post_process
return optimize_pdf(pdf_out, context)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 794, in optimize_pdf
optimize(input_file, output_file, context, save_settings)
File "/usr/lib/python3.8/site-packages/ocrmypdf/optimize.py", line 550, in optimize
pike.save(output_file, **save_settings)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
self.flush()
File "/usr/lib/python3.8/logging/__init__.py", line 1065, in flush
self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
File "/usr/bin/ocrmypdf", line 11, in <module>
load_entry_point('ocrmypdf==9.8.0', 'console_scripts', 'ocrmypdf')()
File "/usr/lib/python3.8/site-packages/ocrmypdf/__main__.py", line 64, in run
result = run_pipeline(options=options)
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 433, in run_pipeline
log.exception("An exception occurred while executing the pipeline")
Message: 'An exception occurred while executing the pipeline'
Arguments: ()
[Errno 28] No space left on device
```

**Comment by jbarlow83** [comment]
No, I think it would be nice to have as a feature. I put some time into deciding whether it was feasible to do right away or defer, decided to defer but wrote my notes here. (Who knows, maybe some enterprising individual will write a PR based on my sketch of how to attack the problem?)

I'm afraid I can't do much about that OSError because that can appear almost anywhere.

The easiest thing you could do is add a USB stick for extra /tmp space. $10 for 32 GB.

**Comment by Denis-Oakley** [comment]
OK, thanks, I've understood. So close it.

**Comment by eMPee584** [comment]
How about adding a command-line option `--tmpdir`? 
Or at least documenting `TMPDIR` in the man page 😀

**Comment by jbarlow83** [comment]
The TMPDIR environment variable is a standard for all POSIX programs.
