### ISSUE TITLE
jbig2 compressed pdf gets way bigger after ocr

### ISSUE THREAD

**Issue by HansBull** [jbarlow83/OCRmyPDF#587]
**Describe the bug**
Creating a jbig2-compressed pdf from jpegs via jbig2 -s -p -v *.jpg && pdf.py output >out.pdf results in 860kb pdf, after ocrmypdf it increases to 6Mb.

**Comment by HansBull** [comment]
Example files (one page only to test)
[out-ocr.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4862371/out-ocr.pdf)
[out.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4862373/out.pdf)

This is with ocrmypdf 6.1.2 from Ubuntu 18.04

**Comment by jbarlow83** [comment]
Most likely ocrmypdf promoted all your file's pages to full color, so it's not a problem with jbig2, but rather the presence of color jpegs. This old version probably predates the page grafting technique I developed that works around this problem - but it's about 50 releases old by this point, I don't remember what it's in it any more.

The documentation has a step by step procedure to install the latest version on Ubuntu 18.04.

**Comment by HansBull** [comment]
Unfortunately 10.2.0 only produces slightly smaller pdfs than the old 6.1.2

**Comment by jbarlow83** [comment]
Sorry about that - yes, 6.1.2 can't do this as well.

I did find an issue where the latest version could potentially downgrade JBIG2 lossy to lossless, which does increase file size.

Also, in the default mode, we produce a PDF/A. Ghostscript replaces all JBIG2 images with CCITT, and we switch them back to JBIG2 by re-encoding them rather than attempting to recover the image from the original file (which would work sometimes, but not in general). Use `--output-type pdf --optimize 0` (disable PDF/A and optimization, since the file is already well optimized).

**Comment by HansBull** [comment]
> Use `--output-type pdf --optimize 0` (disable PDF/A and optimization, since the file is already well optimized).

Very nice, with this setting size goes from 14.4k to only 19.6. I think I can close this.
