### ISSUE TITLE
How to use --rotate-pages in a docker command

### ISSUE THREAD

**Issue by daballiemo** [jbarlow83/OCRmyPDF#589]
**Describe the issue**
I am using OCRmyPDF docker image and would like to change the orientation of landscape pages to portrait. This is possible when using OCRmyPDF from the command line when using the "--rotate-pages" option, but I have no idea how to set this behaviour when using the Docker image.

**To Reproduce**

docker compose file:

version: "2"
services:
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    image: jbarlow83/ocrmypdf:v10.0.0
    volumes:
      - '/volume1/DMS/pre-OCR:/input'
      - '/volume1/DMS/post-OCR:/output'
    environment:
      - OCR_ON_SUCCESS_DELETE=1 
      - OCR_DESKEW=1
      - PYTHONUNBUFFERED=1
      - WATCHER_CHMOD=664
      - OCR_POLL_NEW_FILE_SECONDS=60
      - OCR_ROTATE_PAGES.                            <----------------------------
    entrypoint: python3
    command: watcher.py

**Expected behavior**
Landscaped scanned pages are turned to portrait

**System:**

- OS: Synology DSM 6.2.3-25426 / DOcker 18.09.0
- OCRmyPDF Version: 10.0.0

*

**Comment by jbarlow83** [comment]
There is no OCR_ROTATE_PAGES environment variable. What you can do is define OCR_JSON_SETTINGS as `{ "rotate_pages": true }`. You may also need to define `rotate_pages_threshold` as some value between 0 and 15.

Page rotation detection in Tesseract is somewhat unreliable. It will both miss pages that ought to be rotated, and randomly rotate pages that were already correct.

Aside: the watcher script isn't a turnkey solution. Everyone has a different workflow and should customize it to meet their needs, which is why it's floating in `misc/` rather than a part of the main program.

**Comment by daballiemo** [comment]
Thank you, will have a go at the solution you offered and see if it is usable under the conditions you mentioned.

Adapting the watcher script is something performed within the image I guess. Would it be an option to have the watcher script on a volume then so setup en adaptions are retained over upgrades?

**Comment by jbarlow83** [comment]
Perhaps? I think the watcher design needs to be rethought overall. 

You might need your watcher script to run natively, since watching a mounting file system with docker isn't always reliable. It's definitely unreliable when the underlying filesystem is any kind of network file system.

**Comment by jbarlow83** [comment]
Added this an example of OCR_JSON_SETTINGS to documentation - I'll close the issue now. Please feel free to reopen or open another if you have other questions.
