### ISSUE TITLE
file size increase really caused by pdfa requirements?

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#609]
Version 10.3.2 specifies `--output-type pdf` as a possibility to avoid increasing file sizes, so that the strict pdfa format is not forced, which is said to require file size increase because "PDFA doesn't allow images with Interpolate true".

However, I doubt if this is really the (only) cause, because `pdfimages -list` displays a rgb color profile with 8 bpc for the generated pdfa document, while the input pdf as well as the output generated with `--output-type pdf` has an icc profile with 1 bpc.

Is this conversion of color profile really required for pdfa or is it the same problem as documented in e.g. https://github.com/jbarlow83/OCRmyPDF/issues/506?

As the issue of file size increase is mentioned frequently and the workaround to give up pdfa standard is often no suitable option: Is there a possibility to force 1 bpc or could that please be made available (on the users own responsibility)? That would be really, really helpful for many users as black text on white background is probably the most common application for ocrmypdf.

Thanks a lot in advance!

**Comment by jbarlow83** [comment]
This feature serves to trap files that are getting needlessly inflated and encouraging people to report that. I don't mind if it gets over-reported a little. It often takes something a bit unusual or exotic to trigger at this point.

PDF/A is definitely not the only possible cause. We're trying to enumerate possible causes without, frankly, getting too complicated.

"Interpolate true" means resample the image with a resampling algorithm, rather than replicating pixels (makes a blocky image). Because interpolation algorithms differ, and are not one size fits all, it's not allowed in PDF/A. Images tagged interpolate true can get expanded to a much bigger image, and thus a bigger file. It would probably improve things to not complain about PDF/A unless we interpolate true.

Ghostscript also can't handle some special cases like 1-bit images with icc, and so it falls back to full color. This is harder to detect.

As for color profile: what's going on here is that PDF/A requires at least one "output intent", a description of the target device the file might be displayed on. PDF/A also has to be completely self-contained without any dependency on external resources or data, so we have to embed the sRGB profile with our output intent description. It's 3 KB compressed so not too much trouble, I'd think. AFAIK, no conversion happens at all, we're just providing a reference in case the viewer needs or wants it.  So we pick a sRGB color monitor, because that's a harmless choice. On the other hand the `ColorConversionStrategy` argument to Ghostscript does potentially convert colors whenever deemed necessary. I think this mainly happens for vector objects (perhaps CMYK->RGB), since Ghostscript does not seem to alter images.

**Comment by jbarlow83** [comment]
On a separate note, can you send me your email address?

**Comment by femifrak** [comment]
I am not sure whether i got all the point. Therefore I have 3 questions:
1.) Is an icc profile with 1bpc allowed for pdfa format?
2.) Is icc profile with 1 bpc generally more space saving that rgb with 8 bpc?
3.) If both questions get a yes: Is the reason for not including this feature: ghostscript has no possibility to create files with icc 1bpc, correct?

**Comment by jbarlow83** [comment]
On Thu., Aug. 6, 2020, 05:17 femifrak, <notifications@github.com> wrote:

> I am not sure whether i got all the point. Therefore I have 3 questions:
> 1.) Is an icc profile with 1bpc allowed for pdfa format?
>
Yes, it's allowed

> 2.) Is icc profile with 1 bpc generally more space saving that rgb with 8
> bpc?
>
Yes, at least 8x.

> 3.) If both questions get a yes: Is the reason for not including this
> feature: ghostscript has no possibility to create files with icc 1bpc,
> correct?
>
Yes. For PDF/A it's a special case and Ghostscript handles by converting it
to a wider color depth.

In lossy modes (e.g. deskew), we ask Ghostscript to convert all colors on a
page to the common denominator when creating a page image, because we don't
do page color segmentation to detect what regions can be represented with
lower color depth.

**Comment by femifrak** [comment]
Thanks for your explanations!
