### ISSUE TITLE
No known reason for file size increase (1.43×)

### ISSUE THREAD

**Issue by jangop** [jbarlow83/OCRmyPDF#614]
**To Reproduce**

```bash
ocrmypdf -l deu scan.pdf scan2.pdf
```

**Command Line Output**

```
Scan: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 719.97page/s]
   INFO - Start processing 6 pages concurrently
WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                            
WARNING -    7: [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                            
WARNING -    8: [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                            
WARNING -   11: [tesseract] lots of diacritics - possibly poor OCR                                                                                                                                            
OCR: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11.0/11.0 [00:02<00:00,  3.79page/s]
WARNING - Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
   INFO - Optimize ratio: 1.00 savings: 0.0%
   INFO - Output file is a PDF/A-2B (as expected)
WARNING - The output file size is 1.43× larger than the input file.
No reason for this increase is known.  Please report this issue.
```

[Verbose log with `-v1`](https://github.com/jbarlow83/OCRmyPDF/files/5090343/verbose.log)

**Example file**

[test.pdf (encrypted w/ `gpg`)](https://github.com/jbarlow83/OCRmyPDF/files/5090311/test.pdf)

**Expected behavior**
Smaller output file size or an explanation for the increase.

**System**
 - OS: Ubuntu 18.04.5 LTS
 - OCRmyPDF Version: 9.6.1
 - Installed via `pip` inside a conda environment.

**Comment by jbarlow83** [comment]
Using version 10.3.3 or higher, the file size is not increased, so whatever issue caused this has since been fixed.

You can follow these directions to remove the older Ubuntu version of ocrmypdf and install the newest version:
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-the-latest-version-on-ubuntu-20-04-lts

**Comment by jbarlow83** [comment]
I thought I should clarify that, in newer versions, the file size still increases. The message is now not shown because the increase in file size is expected and unavoidable.

You can get a smaller file using `--output-type pdf` if you do not require PDF/A. In that case the file size change is in line with the overhead of adding OCR.
