### ISSUE TITLE
jbig2 conversion not working?

### ISSUE THREAD

**Issue by Jmuccigr** [jbarlow83/OCRmyPDF#620]
**Describe the bug**
I've got a pdf with a couple of jbig2 images (according to pdfimages). They get converted instead of left alone.

**To Reproduce**
ocrmypdf --optimize 1 (or 3) --force-ocr

**Expected behavior**
jbig2 would be preserved.

**Screenshots**

**System (please complete the following information):**
 - OS: MacOS 10.13.6
 - Python version: Python 3.8.5
 - OCRmyPDF version: stable 11.0.1 (bottled)

**Additional context**

**Comment by jbarlow83** [comment]
With `--force-ocr` everything will be promoted to the highest common colorspace (i.e. if there's a small color image, everything gets converted to color). If there is only black and white on the page then there may be some other problem. You could use `--keep-temporary-files` and look at the intermediate images to see when the colorspace promotion happens; that may help.

Color segmentation is doable but would be time consuming to implement. Frankly it's the sort of feature that is waiting for someone to sponsor it or do a PR, because otherwise I wouldn't be able to justify the time.

**Comment by jbarlow83** [comment]
See also https://github.com/jbarlow83/OCRmyPDF/issues/557

**Comment by Jmuccigr** [comment]
The temp png files are all 8-bit sRGB, says `identify`, even though they're the only things on the page and pdfimages reports them as jbig2 in the pdf. This is the case even when the file has only jbig2 images. Outputting those images with `pdfimages -all` gets me jb2e files that I can't open.

**Comment by jbarlow83** [comment]
What do the image object dictionary and content stream look like? Colorspace promotion can happen if the content stream selects a color at some point, e.g. to draw a vector line or print text. If the image object dictionary has certain "fancy" features, we also assume it's color. Acrobat's Preflight tool can read content streams, or you could use pikepdf to find them.

**Comment by Jmuccigr** [comment]
It's the same file that I posted for #621.

**Comment by jbarlow83** [comment]
In that file page 1 will be promoted to full color because of the color image in the bottom left. 

For pages 2 and 3 the text at the bottom "This content downloaded from...", a CMYK color is selected (although it is pure black). This also triggers promotion to full color.

With `--optimize 3` the first page is collapsed to a palette of 4 colors, and the other two to 2 colors. We can't do color segmentation but we can do imagewise color reduction with pngquant. Typically we'd get two monochrome colors at this stage, and then realize we can convert to JBIG2, and this would happen regardless of whether the input was JBIG2.

But, for reasons not entirely clear to me, pngquant produces a 1-bit image with a color palette (colormap), whose entries are:
```
  Colormap:
    0: (1,1,1,1) #010101FF srgba(1,1,1,1)
    1: (255,255,255,1) #FFFFFFFF white
```

So it's not exactly pure black (0,0,0). The Leptonica image library, which we used to open the saved image, seems to silently convert this 1-bit image with its useless palette to 8-bit grayscale. Since Leptonica declares it to be 8-bit grayscale, ocrmypdf no longer considers it a candidate for JBIG2 optimization which requires 1-bit. 

You've found a subtle bug that involves an interaction of two different libraries.

It looks like I should be able to fix this by adding another step to optimization of explicitly checking the number of colors in the image and applying JBIG2 if it's exactly 2, and setting up a colormap. (Note to self: Pillow can't extract the palette exactly, but `im.getcolors()` returns the expected results, Leptonica seems to be pretty confused by the situation.)
