### ISSUE TITLE
Having trouble with --remove-background option.

### ISSUE THREAD

**Issue by anaxonda** [jbarlow83/OCRmyPDF#628]
**Describe the bug**
I'm having trouble removing a yellowish/gray background from a file. The file already has existing OCR that ideally I would like to ignore. The --remove-background option only seems to work if --force-ocr is on, and not --skip-text.
However, if I choose this method the resulting file is 4.46x bigger.
Thank you for any help!

**To Reproduce**
What command line or API call were you trying to run?

```bash
ocrmypdf --tesseract-timeout=0  --remove-background --deskew --clean --clean-final --skip-text --optimize 3 --output-type pdf in.pdf out.pdf

```

**Example file**
https://drive.google.com/file/d/1yIb0aHqkB3pQ5uQUDTbIjVw5hvcjCaXn/view?usp=sharing

**Expected behavior**
Background will be removed.

**Screenshots**
Here is how the pdf looks like after the --force-ocr option (ideally I would get this result with '--skip-text' instead: 
![image](https://user-images.githubusercontent.com/15372684/92525326-3eb5d780-f1e9-11ea-9ec1-e67f197a0dc4.png)

**System**
 - OS: linux
 - OCRmyPDF Version: 11.0.1
 - How did you install ocrmypdf? Arch User Repository

**Comment by jbarlow83** [comment]
Can you share the PDF with me? Google Drive wants you to approve an access request.

`--skip-text` will ignore pages that have text already. (`--redo-ocr` might help, but cannot detect all types of OCR so can't redo everything.)

The file size increase with `--force-ocr` is likely due to colorspace promotion.

**Comment by jbarlow83** [comment]
(Tagged as need test file since I cannot access the test file.)

**Comment by anaxonda** [comment]
Oops, I've granted you access to the pdf, sorry about that. Thanks

**Comment by jbarlow83** [comment]
Thanks for enabling access to the file.

The issue that the options `--remove-background --deskew --clean --clean-final` all require us to render the PDF page (in general, a complex vector artwork object) into a single, full page image and process it. We don't have the ability to analyze the PDF page and rationally apply those raster image-specific operations to a vector object. So in a way, `--force-ocr` is where the program steers you, because it's the only option.

Your PDF actually has three images per page - there's a low resolution color image, a high resolution color image, an image mask, and of course the OCR layer is entangled with this.

```
> pdfimages -list issue628.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     866  1421  rgb     3   8  jpeg   no         9  0   168   167 17.2K 0.5%
   1     1 image    2597  4261  rgb     3   8  jpeg   no         8  0   502   501 96.7K 0.3%
   1     2 mask     2597  4261  -       1   1  jpeg   no         8  0   502   501 96.7K 7.2%
   2     3 image     866  1421  rgb     3   8  jpeg   no        12  0   168   167 13.5K 0.4%
   2     4 image    2597  4261  rgb     3   8  jpeg   no        11  0   502   501 99.1K 0.3%
   2     5 mask     2597  4261  -       1   1  jpeg   no        11  0   502   501 99.1K 7.3%
   3     6 image     866  1421  rgb     3   8  jpeg   no        15  0   168   167 18.8K 0.5%
   3     7 image    2597  4261  rgb     3   8  jpeg   no        14  0   502   501  112K 0.3%
   3     8 mask     2597  4261  -       1   1  jpeg   no        14  0   502   501  112K 8.3%
```

To deal with this file, OCRmyPDF rounds up both the resolution and color space, which is why the file grows so much. But I suspect if you install pngquant you'll get better optimization results. I got a ~50% larger file which is not bad for 500 DPI:

```
> pdfimages -list issue628_out_force.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2597  4268  index   1   2  image  no        20  0   502   502  187K 6.9%
   2     1 image    2597  4268  index   1   2  image  no         3  0   502   502  207K 7.7%
   3     2 image    2597  4268  index   1   4  image  no         7  0   502   502  265K 4.9%
```

What I recommend you do is write a small custom plugin that overloads `filter_ocr_image` and returns an image that is 1 bit per pixel, e.g. using Pillow's `Image.convert('1')`:

```python
# mono.py
from ocrmypdf import hookimpl

from PIL import Image
from pathlib import Path

@hookimpl
def filter_page_image(page: 'PageContext', image_filename: Path) -> Path:
    with Image.open(image_filename) as im:
        im = im.convert('1')
        im.save(image_filename)
    return image_filename
```

Then use:

```
ocrmypdf --tesseract-timeout=0  --remove-background --deskew --clean --clean-final --force-ocr  --optimize 3 --plugin mono.py  --output-type pdf issue628.pdf out_force_mono.pdf
```

The resulting file is 182K, compared to the input file at 402K.

It is be possible to graft the existing OCR layer onto the PDF and avoid losing the existing OCR, but that would also be a lot of trouble to get working. At least for the moment, I see an "almost" way to do that easily, but not a direct path.

**Comment by anaxonda** [comment]
Great explanation, thanks!

After installing pngquant, and running with that python plugin, results are very satisfactory for my needs. One thing I did notice is that OCR does not work after.

I needed to redo the ocr on the resulting file:
`ocrmypdf --redo-ocr out_force_mono.pdf out.pdf`



Otherwise I'm happy.
