### ISSUE TITLE
INFO -    1: page has no images - skipping OCR

### ISSUE THREAD

**Issue by jowenn** [jbarlow83/OCRmyPDF#63]
Hi!

I have some PDFs I know that have a full screen image, but ocrmypdf 4.0.7 tells me, that there is no image on the page.

The relevant part in the PDF looks like:
9 0 obj
<<
/Type /XObject
/Subtype /Image
/Width 2480
/Height 3507
/BitsPerComponent 1
/ImageMask true
/Length 38132
/Filter [/ASCII85Decode /CCITTFaxDecode]
/DecodeParms [null << /K -1 /Columns 2480 >>]
>>
stream

If I comment the ImageMask check in _find_page_images in pageinfo.py on lines 207-209:
#        if '/ImageMask' in pdfimage:
#            if pdfimage['/ImageMask']:
#                continue

Everything appears to work fine.

What is this check for, what breaks in general, if that check is removed? Would a PR be accepted, that makes this check configurable optional?

**Comment by jbarlow83** [comment]
Sorry I missed this inquiry earlier.

`/ImageMask` means the the image is a stencil mask for a grayscale or color image. As far as I can tell whatever program creates your PDFs is setting this attribute incorrectly. Could you send me one of the PDFs? I'd like to see if there is anything else unusual about them. According to PDF spec you're supposed to use masks to help draw other images rather than draw masks explicitly, although drawing masks is not forbidden.

This code in that function is figuring what resolution to rasterize each page at without losing information. In the event that the image mask is higher resolution than the input image, the composite image should be drawn at the highest DPI to accurately capture the effect of the mask. It looks like the right to do is take masks into account rather than ignore them (a holdover from earlier, less robust versions), as your change proposes.

**Comment by jowenn** [comment]
I cannot give you the PDFs I have right now, but I'll try to get some of the same kind without sensitive data. I let you know when I have them

**Comment by jbarlow83** [comment]
Should be fixed in 4.1.
