### ISSUE TITLE
Add example web service

### ISSUE THREAD

**Issue by hong4rc** [jbarlow83/OCRmyPDF#630]
**Describe the bug**
I open web service via docker. It works fine in browser, but I try use `axios` (added `httpAgent`+`timeout` in option, added `Connection: 'keep-alive'` in headers) to request OCR a file and get this result:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```
Can you add a example to get response file OCR-ed with web service with any language?

Thank you

**Comment by jbarlow83** [comment]
The web service is really quite rudimentary - just a proof of concept. It's good enough for small deployments and casual use, not much more. If I understand what you're looking for, I don't know how to do that, not without doing some research anyway.

If you want to suggest improvements we could discuss. I don't know Node.js and wouldn't accept a solution built around that because keeping everything in Python keeps testing simpler.

**Comment by hong4rc** [comment]
> The web service is really quite rudimentary - just a proof of concept. It's good enough for small deployments and casual use, not much more. If I understand what you're looking for, I don't know how to do that, not without doing some research anyway.
> 
> If you want to suggest improvements we could discuss. I don't know Node.js and wouldn't accept a solution built around that because keeping everything in Python keeps testing simpler.

Can you create simple code to request OCR file via web service with Python(or any language you want)?

I want to know what I missing when request OCR via web service through your code.

**Comment by jbarlow83** [comment]
It creates an HTML page when you browse to / that demonstrates its protocol.

**Comment by jbarlow83** [comment]
I'll close this now - adding a more complex web service is just not something I can take on at this time.

**Comment by hong4rc** [comment]
Can I request OCR file via postman?

I alway get return code `400` :(
