### ISSUE TITLE
Setting --tesseract-timeout=0 on a file with no OCR, still spend many time on the OCR stage

### ISSUE THREAD

**Issue by wpzdm** [jbarlow83/OCRmyPDF#647]
**Describe the bug**
According to the [docs](https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#don-t-actually-ocr-my-pdf), we can skip OCR by setting` --tesseract-timeout=0`. But if the file has no OCR, it will still spend many time on the OCR stage.
Adding  `--skip-text ` only helps when the file already has OCR. It seems `--tesseract-timeout=0 ` has no effect.

**To Reproduce**
ocrmypdf --tesseract-timeout=0  --optimize 3 --jbig2-lossy  input.pdf output.pdf
input.pdf has no OCR.

**Expected behavior**
Skip OCR stage with no time.

**System (please complete the following information):**
 - OS: macOS 10.15.4 
 - Python version: Python 3.8.1
 - OCRmyPDF version: 11.1.2

**Comment by jbarlow83** [comment]
At the "OCR" step in processing, both image processing and OCR happen (with OCR being a no-op when its timeout is 0). So it's working as it should, and it still needs some time even then there is no OCR. A little bit of this work could be optimized out in the no-OCR but I don't think it's worth special casing that.

I'm changing the text label describing this phase to read "Image processing", because I can see it would look like OCR is happening when it isn't wanted, and that would look alarming.

**Comment by jbarlow83** [comment]
Fixed in 6be2242c

**Comment by wpzdm** [comment]
Could you explain the difference between `--tesseract-timeout=0` and `--tesseract-timeout=0 --skip-text`? It cannot be seen clearly from current docs. 
I feel `--skip-text` is like "check if we already have OCR, and if so, skip OCR stage". And if we can skip OCR stage with no time in this case, it is a bit strange we cannot when there is no existing OCR. I guess there are some details I do not know.

Could you also explain what image processing is done when `--tesseract-timeout=0`?
The time spent in OCR stage is quite long even with `--tesseract-timeout=0`, at least half of the time of a complete OCR.

**Comment by jbarlow83** [comment]
>I feel --skip-text is like "check if we already have OCR, and if so, skip OCR stage". 

More precisely, it will skip all processing of pages that already have any text, whether from a font or OCR. This is useful if you have a document that contains a mixture of scanned images and "born digital" content. Pages that have digital content are not touched. If you used `--deskew --skip-text`, pages that have existing text will not be deskewed.

>Could you also explain what image processing is done when --tesseract-timeout=0?

All of the processing that would normally occur, leading to, in the general case, two images: an image we show the OCR engine (OCR image), and an image we show to the user (presentation image), which are not necessarily the same. We feed the OCR image to Tesseract, and then kill the Tesseract process immediately because the timeout is 0. If an image processing command like `--deskew` was issued we replace the whole page with the presentation image. If no image processing commands were used such that the original page is identified to the presentation image, the presentation image is not used.

Combining the results into a single final PDF is effectively single-threaded, which is likely where the delay comes from.

**Comment by wpzdm** [comment]
>  We feed the OCR image to Tesseract, and then kill the Tesseract process immediately because the timeout is 0. 

It seems we need a `--no-ocr` command to skip all processing related to OCR, including OCR image. `--tesseract-timeout=0` is a compromise when we do not have that command. 
Of course, it is a bit weird to add `--no-ocr`  into a tool that is made for OCR. Still, I find OCRmypdf handy for post-processing, like image optimization and save to PDF/A.
