### ISSUE TITLE
The Postprocessing step uses only one CPU core

### ISSUE THREAD

**Issue by wpzdm** [jbarlow83/OCRmyPDF#656]
**Describe the bug**
The Postprocessing step uses only one CPU core. I can observe using `top` that there is a `gs` process that uses less than 100% CPU.
In a 32 core machine, Postprocessing is tens of times slower than OCR.

**To Reproduce**
Run ocrmypdf on a multi-core processor.

**Expected behavior**
It would be great that in Postprocessing step we can also have speed-up proportional to CPU core number (Like in OCR step).

**System (please complete the following information):**
 - OS: macOS and also Linux
 - Python version: unrelated I believe
 - OCRmyPDF version: 11.2.1

**Comment by jbarlow83** [comment]
Ghostscript does not use all cores, so there is no way to speed this up since all of the work is delegated to Ghostscript. `--output-type pdf` does not use Ghostscript and is faster but still not parallelized or easily parallelizable.

(There are some operations where Ghostscript uses multiple threads, but pdfwrite is not one of them.)
