### ISSUE TITLE
Question : OCRmyPdf in RHEL 7.x

### ISSUE THREAD

**Issue by manshapandey** [jbarlow83/OCRmyPDF#662]
We are able to install base package (ocrmypdf) using using **pip3** . However, some dependencies are not available in RHEL for example, liblept . (https://pkgs.org/download/liblept.so.5). 

So my question is how to install OCRmyPDF in RHEL 7.x with all the dependencies included ?What are options available. So far in the documentation we don't see installation instructions for RHEL.

Any pointers are highly appreciated.

Thanks, 
Mansha

**Comment by jbarlow83** [comment]
RHEL 7 is older than the first release of OCRmyPDF. The easiest route is to use a Docker container or similar virtualization service. Otherwise, you'd be looking at building a large stack of dependencies from source.

The OCRmyPDF Docker image is based on Ubuntu. If you prefer to stick with the Redhat ecosystem you could derive an image from Fedora, which now includes OCRmyPDF.

**Comment by jbarlow83** [comment]
If you happen to create steps for RHEL 7 or 8 or CentOS I'd be happy to add them but I don't think I will do so myself since OCRmyPDF is already in Fedora and should make its way into RHEL eventualy.

I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by manshapandey** [comment]
Thank you @jbarlow83 for your input. I will try it and will update it here.
