### ISSUE TITLE
Issue running OCR API inside Celery

### ISSUE THREAD

**Issue by nonprofittechy** [jbarlow83/OCRmyPDF#666]
**Describe the bug**
OCR process hangs indefinitely when called from inside Celery. Works fine when called directly using the API.

**System (please complete the following information):**
 - OS: Debian 10
 - Python version: 3.6
 - OCRmyPDF version: 11.2.1

**Additional context**

I am trying to integrate ocrmypdf for a project built around https://github.com/jhpyle/docassemble, where it would be extremely useful. We need to reduce the file size of pleadings to send to court, where the email size limit is just 15 MB.

ocrmypdf is working great in a foreground process. As soon as I send it to the background task system in docassemble, which is built on celery, it runs forever without returning any progress. I'm wondering if you have any suggestions. The first thing I caught was an AssertionError when I didn't have `use_threads=True` set. It was returning status right away with the AssertionError. But once I set it to run threaded, it no longer finishes the celery task.

I am calling it like this:

`ocrmypdf.ocr(file_temp.path(), self.ocr_doc.path(), progress_bar=False, deskew=True, optimize=3, skip_text=True, use_threads=True)`

**Comment by jbarlow83** [comment]
Please read this section of the documentation if you haven't already. In particular make sure you set up logging and check the assumptions ocrmypdf makes about the system.
https://ocrmypdf.readthedocs.io/en/latest/api.html

Also have a look at `ocrmypdf/_concurrent.py`.

You do not necessarily need or want `use_threads=True`. The main use of that it is makes running ocrmypdf in a debugger much easier. It's worse in all respects otherwise. This argument is also a slight misnomer: it means that threads will be used as workers, instead of processes; there is a still `log_listener` thread created in the main process to receive log messages from the workers, regardless of the workers' execution context.

ocrmypdf cannot run tasks on distributed workers. Workers assume they are running on the same filesystem as other workers.

While the caveat that I'm only passingly familiar with Celery, I tend to think the ideal solution would be to write an ocrmypdf plugin that overrides `ocrmypdf._concurrent.exec_progress_pool` and uses Celery's API to schedule tasks. (Currently, there is no plugin hook for that, but it's an easy change on my end.)

**Comment by jbarlow83** [comment]
ocrmypdf v12 adds a plugin hook that allows overriding the parallel executor, which should make it possible to replace the one with Celery.
