### ISSUE TITLE
No logging output when using Docker and watcher.py

### ISSUE THREAD

**Issue by teaker** [jbarlow83/OCRmyPDF#669]
**Describe the bug**

When using the docker image and watcher.py, only the logging in main() works.  No subsequent logging information is available.

**To Reproduce**
Command:  
```bash
docker run \
    -v /mount/ocrin:/input \
    -v /mount/ocrout:/output \
    -e OCR_OUTPUT_DIRECTORY_YEAR_MONTH=1 \
    -e OCR_ON_SUCCESS_DELETE=1 \
    -e OCR_DESKEW=1 \
    -e PYTHONUNBUFFERED=1 \
    -it --entrypoint python3 \
    jbarlow83/ocrmypdf \
    watcher.py
```

Upon running the above command, the following is printed to the terminal:
```
Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output directory Year & Month: True
```
<No further logging occurs beyond this point>

**Expected behavior**
When watcher.py detects a new file in the Input Directory, additional logging/status should print to the terminal.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Docker: 19.03.13
 - Python version: 3
 - OCRmyPDF version: latest docker build

**Comment by jbarlow83** [comment]
Try setting the environment variable `USE_POLLING=1` to force repeated directory polling instead of using OS services (e.g. inotify) to monitor the directory.

Files which do not end in `.pdf` will be ignored. This includes `.PDF` (minor bug).

First try to get this working with a volume that is a local to the Docker host machine. For example try `/home/user/test`. Use `docker run -it --entrypoint /bin/bash jbarlow83/ocrmypdf` and test that the Docker container can actually read and write `/input` and `/output`.

If you try to provide a network share as the volume, or another Docker container, that can work but may not be as reliable.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
