### ISSUE TITLE
API: Provide a progress callback for displaying progress in applications that use ocrmypdf.

### ISSUE THREAD

**Issue by jonaswinkler** [jbarlow83/OCRmyPDF#685]
**Is your feature request related to a problem? Please describe.**
I'm using the ocrmypdf API in an application and would like to pass information about the progress on PDF documents to the end user. I'd like to have a progress bar in a gui, and for that I need more than just a progress bar printed to stdout. Besides, the end user does not even get to see the output of ocrmypdf.

**Describe the solution you'd like**
Implement a callback that gets called whenever the progress changes. Callers of ocrmypdf may then visualize the progress in any way they want (GUI, send messages over web sockets, etc).

This is what it would look like:

```
def my_callback(current, max):
    # example, but you get the idea.
    my_graphical_progress_bar.set_current(current)
    my_graphical_progress_bar.set_max(max)

ocrmypdf.ocr(input, output, other_args, progress_callback=my_callback)
```
**Describe alternatives you've considered**
Well, as far as I know there are no alternatives right now.

**Additional context**
If this is a wanted feature I'd look into the implementation myself.

**Comment by jbarlow83** [comment]
Currently there's no official way to do this. In principle you could monkeypatch tqdm (the existing progress bar module ocrmypdf uses) into doing the job.

The way it should be done is to provide a plugin that allows the replacement of tqdm with another progress interface, similar to how Ghostscript and Tesseract are now technically plugins. My plan is to make most things pluggable eventually. For the progress bar, the way we'd go is to add a new API to `ocrmypdf.pluginspec`, which ocrmypdf will call when it wants to set up a progress bar, and the default plugin will just call `tqdm.tqdm`, but you could supply an alternate plugin. If you want to do this as a PR I'd be happy to support the change, otherwise I don't see this as a particularly high priority task myself so I'll "get there when I get there".

Unfortunately some subtasks ocrmypdf does don't give good feedback of their progress.

I'm curious - what application are you working on?

**Comment by jonaswinkler** [comment]
Huh, somehow I missed the notification.

I'm working on a lightweight document management system (scan in physical documents, archive and index them, destroy the originals). It uses your library to perform OCR on documents and add text layers to documents. Having selectable text on any document is a huge plus when copying data from documents into meta data fields. Since OCR may take quite a bit of time, I'd like to show some progress bar on the web front end with web sockets.

I've looked into the source a bit since opening that issue, and I can see why it's not all that easy. Thanks for the pointers, I might look into that. It's not on high priority over here either.
