### ISSUE TITLE
Break text when nothing to OCR

### ISSUE THREAD

**Issue by sstefanov** [jbarlow83/OCRmyPDF#689]
**Describe the bug**
Text is broken even when OCR is skipped

**To Reproduce**
Command line is here:
```bash
ocrmypdf -k -v1 -d -s test.pdf testocr.pdf
```

**Example file**
File is GPG encrypted:
[test.gpg.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5664025/test.gpg.pdf)

I know original file have some errors, but it is readable and text is OK. After command text is still here, but it is like some chinese letters.

Debug log is here:
[debug.log](https://github.com/jbarlow83/OCRmyPDF/files/5664027/debug.log)

**Expected behavior**
When OCR is skipped do not change it even when source file have errors.

**System**
 - OS: Linux
 - OCRmyPDF Version: 11.3.4
 - installed by pip

**Comment by jbarlow83** [comment]
As far as I can tell this is a bug in Ghostscript, which ocrmypdf uses. Using Ghostscript to rewrite the PDF will damage the text encoding of the file in the same way:
`gs -sDEVICE=pdfwrite -o _gs.pdf issue689.pdf`

Since this is an encrypted file transmitted to me in confident, I would not send it to anyone else. But please consider submitting it to https://bugs.ghostscript.com/, to see if they will take a look at the issue your file exposes. Perhaps they can accepted encrypted files in some way. I think Ghostscript should refuse to the process the file instead of damaging it, if they can't fix whatever issue is present.

As a workaround with ocrmypdf, you can add `--output-type pdf` the text will remain readable (and the font problems will remain too).

Ideally, you should use `--force-ocr` on this file. The embedded fonts in this file are probably damaged or malformed in some way, and the best way to ensure future software will read it is to use force (turn the file into an image, and add an OCR text layer).

**Comment by jbarlow83** [comment]
Closed - primarily a third party issue.

Might be possible to detect when gs will have this problem. Should look into that if multiple files have this problem and GS doesn't fix it.
