### ISSUE TITLE
Skip "text-based" pdfs when batch processing (or at all)

### ISSUE THREAD

**Issue by sgjohnson1981** [jbarlow83/OCRmyPDF#697]
Not sure if this is a feature request, bug, or user error, but...

**Is your feature request related to a problem? Please describe.**
I noticed some weird characters cropping up in the text preview pane of searchmonkey, so I thought maybe the OCR was wonky. It wasn't until I tried copy/paste from the newly OCRmyPDF'ed pdf and original that I realized it wasn't an image-based PDF anyway. But the only useful message I received from OCRmyPDF (using redo-ocr) was something like "some characters can't be mapped: consider using --force-ocr"

**Describe the solution you'd like**
Assist me in figuring out what's going on here? Devise a way to skip "text-based" PDFs (especially in batch processing)?

**Describe alternatives you've considered**
Just figure out a way to discern which pdfs are image-based vs text-based and export all the text-based into image-based and OCRmyPDF them.

**Comment by jbarlow83** [comment]
You most likely found a PDF with a corrupt Unicode mapping. That is, the PDF defines a font, but it doesn't describe the relationship between the characters in that font and Unicode, so it doesn't know that character number 123 is Unicode U+0041, (capital A). It just runs some code for "character 123" to draw that character, oblivious to its meaning. So it can draw the font perfect, but it can't provide copy and paste or search.

Some PDF viewers assume that a font with no Unicode table is ASCII encoded, because some PDFs are made that way. But it's just a guess, and if they guess wrong the user sees gibberish. Most of the time, people are not generally PDFs with these problems any more; in my experience it's most common in software from the 1990s. (It's also allowed to have no Unicode mapping. Maybe your PDF uses a custom font for an ancient language with no Unicode characters assigned.)

The extra analysis run by redo-ocr can be slow on some documents, so it's not always done for users who are concerned about speed. We have to do a deep dive inside the fonts.

The best way to fix it is use force-ocr as suggested. You'll go from having a 0% searchable PDF to 99% searchable.

**Comment by jbarlow83** [comment]
You can already skip text based PDFs in batch processing. If you don't specify any mode argument (--skip-text --force-ocr --redo-ocr), OCRmyPDF will skip the file.

**Comment by sgjohnson1981** [comment]
OK, so how would I batch process text-based PDFs I want left alone along with image-based where I'd like to redo the OCR?

**Comment by jbarlow83** [comment]
For that kind of custom logic, you could write a plugin that overrides the `validate` hook. You would run with `redo-ocr`, and then inspect the results of the analysis and modify the options or raise an exception to halt processing on the file.

**Comment by jbarlow83** [comment]
See `misc/example_plugin.py` for more on making plugins.

I'll close the issue now. If you have further related questions feel free to reopen it.
