### ISSUE TITLE
Provide the text files corresponding to each page instead of using Tesseract

### ISSUE THREAD

**Issue by akelai** [jbarlow83/OCRmyPDF#707]
I'd like the possibility of providing text files as input together with a scanned (handwritten) PDF, to produce a searchable PDF that uses the words in the text files. No need to have matching positions of scanned words and text area: just to be able to search something and jump to a scanned (handwritten) page containing that string, would be great.

I'm not sure if that's already possible (in some way).

**Comment by jbarlow83** [comment]
This would be a hacking project, out of scope of ocrmypdf. What you could
do is is hocrtransform.py as a basis, but instead of positioning each word,
you'd locate them all off of the page, outside of the MediaBox. Then see if
PDF viewers tolerate it. You could replace tesseract with a custom "OCR"
engine that provides your text.

There is a problem in that OCR was added to PDF as an afterthought and is
mainly done by typing invisible text all over the document. Or in some
cases, visible text with an opaque image on top. There is no official way
to correlate search terms to a page without specificying a position on that
page.

**Comment by akelai** [comment]
Thanks, that's a good strategy!
