### ISSUE TITLE
How does Watcher.py work

### ISSUE THREAD

**Issue by Alwiz79** [jbarlow83/OCRmyPDF#714]
Hi!
Can somebody explain to noob how the watcher.py works?

I have everything setup (installed OCRmyPDF, network drives mounted, etc...all on raspberry pi4).
Now I want my network scanner to scan to nas.
Have watcher.py watch an input folder.
Start OCRmyPDF
Either rename the OCRed files or move them to another folder, so that at the end the overwatched input folder is empty again.

I think this is possible with watcher.py, I just dont know how and am limited in my linux know how.

Thanks

**Comment by jbarlow83** [comment]
Well, how it works is people submit changes to watcher.py and I accept them because it's not part of the core program and I keep hoping someone else takes over of it and makes it good... but I digress.

File watching over a network is really problematic and prone to failure. NFS doesn't allow a client to subscribe to push notifications. SMB has this capability but I don't believe the Linux kernel can use it, so you can't subscribe to push notification of file system changes on a network. If the watched folder tree is large, all this polling can be quite pathological for performance. If at all possible you want the watched folder to have direct physical to the file system, not running it any sort of container or network.

Oh yeah. File systems are also bad about detecting when a file is "finished writing, for real". Sometimes because the program that writes them to disk issues multiple open and close calls. So we have a pernicious problem with trying to process files before they're fully written.

Normally you run watcher.py defining a bunch of environment variables, e.g. something like
```
env OCR_ON_SUCCESS_DELETE=1 OCR_INPUT_DIRECTORY=/var/input OCR_OUTPUT_DIRECTORY=/var/output python watcher.py
```

It's far better to have distinct input and output trees. You don't want your output to be a sub-tree of your input, and you don't want to rename files in place inside your input tree.

**Comment by CWempe** [comment]
If you use docker, have a look at this project.

https://github.com/bernmic/ocrmypdf-watchdog

I just installed it and it works as expected.
I copy a PDF to my "input" folder of my NAS and after a short time I get a OCR'd pdf in my "output" folder.

Yo can probably use the includes go file without docker, but I don't know anything about go.
I guess the go file does the same your `watcher.py`.

**Comment by williamthrilliam** [comment]
Also noob question, where is watcher.py located in debian?

**Comment by jbarlow83** [comment]
You'll need to clone the Git repo since it's not automatically installed. 

It's not really a full solution anyway. The assumption is that you'll need to customize the script.
