### ISSUE TITLE
OCRmyPDF is not recognized when using Microsoft Store edition of Python

### ISSUE THREAD

**Issue by Mennaruuk** [jbarlow83/OCRmyPDF#719]
**Describe the bug**
OCRmyPDF is not recognized when using Python 3.9 from the Microsoft Store.

**To Reproduce**

1. Download Python 3.9 from Microsoft Store
2. Install OCRmyPDF by entering this command: `pip install ocrmypdf`
3. Enter this command: `ocrmypdf`

**Expected behavior**
OCRmyPDF should be recognized. It is not. I'm guessing this is an issue with paths. I added the folder where `ocrmypdf.exe` is located to my user environment variables path list, but that didn't do much.

**Screenshots**
Something similar to this. Just replace `ping` with `ocrmypdf`.
![image](https://user-images.githubusercontent.com/52135169/104879031-0f4b7000-592b-11eb-8391-d4751bf389f5.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9
 - OCRmyPDF version: 11.5.0

**Workaround**
The workaround is installing Python 3.9 directly from [Python's official website](https://www.python.org/downloads) rather than Microsoft Store. I want to know if there is any way to solve this for people who do rely on Microsoft Store edition so that they won't resort to uninstalling then reinstalling as I did.

**Comment by jbarlow83** [comment]
I've found a number of other people with questions and complaints about the Microsoft Store version of Python with respect to other packages, so this is a general problem with that version of Python. I'll change my install documentation to recommend against that version, but otherwise there is little that can be done until Microsoft fixes the issues.
