### ISSUE TITLE
Can OCRmyPDF detect if PDF is already /A (test searchable)

### ISSUE THREAD

**Issue by perrygarrod** [jbarlow83/OCRmyPDF#72]
Currently I intend to use OCRmyPDF for a selection of PDF's, but occaissionaly I note that the PDF source is already text searchable and therefore does not actually need to be "converted".
Is it possible to have an option than signifies this situation in some way, or simply creates a copy of the original which would, I assume be far quicker that the conversion process.
Thanks
Perry

**Comment by jbarlow83** [comment]
Ocrmypdf attempts to detect OCR text on a page by page basis. If OCR text
exists, it can abort conversion (default), include the page without
modification (-s, the option you probably want), or rasterize the page
anyway (-f) to do over the OCR.

If you found text that is not text or affected by the switches above please
send me a copy of the file. The manner in which text is detected is
imperfect and may not catch all cases.

**Comment by jbarlow83** [comment]
I should mention I believe there is a case where born digital text will be
skipped.

It may be helpful to set verbose output which comments on this (-v 1).

**Comment by perrygarrod** [comment]
Hi James.
All working but this is odd.  I'm using the --skip-text option, which worked well on a "good" version, albeit the output was slighly bigger than the original despite being a "full" text seachable input file.
However, I'm attached another one where the source isn't so good, is text searchable, but the output "looses" the text searchable words because it's broken each down, as though inserted spaces between each letter, at least in the opening pages.
Not sure resolveable
I've tried zipping, but file sizes are circa 25MB.  Any way I can get them to you?
Thanks
Perry

**Comment by jbarlow83** [comment]
Even with --skip-text the PDF gets rebuilt by Ghostscript so the file size
can change. If the file happens to contain patented compression Ghostscript
will change it to a free algorithm which can occasionally cause bigger file
size changes.

Sometimes OCR fails to group letters to words and such. Or maybe it's
something else. I'll look.

Send a Dropbox link for file transfer?

**Comment by perrygarrod** [comment]
Ji James
I dropboxed the file.
I have however routed, or more precisely captured the output messages from OCRmyPDF, or perhaps I should say Tesseract, which subsequent to processing I check to see what INFO and Warning messages are output as part of the conversion process.  
If I detect the password or the Text found messages, I handle the source file in an appropriate manner.
For P/W protexted, I rename the source and copy it to avoid re-trying future OCR on it.
For "text found", I use the source file, copying it as opposed to anything output from OCRmyPDF, given the issue(s) idetnified earlier.

Once again, thanks for all your help.

Perry

**Comment by jbarlow83** [comment]
I had a look at the files.

Your PDF was produced by tesseract 3.05.00dev in PDF output mode. tesseract inserts OCR text information as an invisible font. It seems that something is wrong with the invisible tesseract font, and Ghostscript misinterprets it, adding spaces where they should not be. The issue is probably with tesseract but it could be ghostscript too.

ocrmypdf is not involved. If I bypass ocrmypdf and tell ghostscript to rewrite the PDF, it will damage the OCR layer in the manner you describe.

``
gs -dQUIET -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -o _gs.pdf ~/Downloads/INPUT.PDF 
``

If you want to use ocrmypdf with these files, use `ocrmypdf --force-ocr`. That tells it to throw away the hidden text produced by tesseract and redo OCR. This should work fine.

A few questions:
* Can I share one page of this file with the tesseract or ghostscript developers?
* There should be a file on your machine with a pathname that ends with "tessdata/pdf.ttf". Could you run  `md5sum tessdata/pdf.ttf` and check if it is `9a91ca4a0de91e9809994992c1d902cc` or some other value? This is the font file tesseract uses. I'd like to see what version is on your machine.

**Comment by jbarlow83** [comment]
Regarding passwords, if you know the password you can use `qpdf`, one of ocrmypdf's dependencies, to remove password protection, prior to running ocrmypdf. qpdf can remove restrictions (e.g. viewing file allowed but changes disallowed) without the password, otherwise it needs the password because the PDF itself is encrypted. Another utility, `pdfcrack` can recover passwords if desired, although this program may not be legal in all jurisdictions.

**Comment by perrygarrod** [comment]
Hi James
Happy for you to pass on page of the offending doc.
I'll place file in Drop Box for you as command md5sum does not work in Dos
[pdf - Copy.txt](https://github.com/jbarlow83/OCRmyPDF/files/325570/pdf.-.Copy.txt)

**Comment by perrygarrod** [comment]
Hi Jim
Have just Dropboxed you another example of a PDF form that is causing me an issue, as I / we dont seem to recognise it's already text searchable, and fails OCRmyPDF
Any pointers how I can recognise these forms would be good
Thanks
Perry

**Comment by jbarlow83** [comment]
The PDF security handler is not supported by the open source library I use to examine the PDF. The only thing I can do at this point is print a better error message.

If you have Acrobat and the password you may be able to remove the security.

**Comment by perrygarrod** [comment]
Hi.  A unique message for this type of file would be good.  If the message could indicate whether or not the document contained text, that would be even better as I'd know what to do with it.

As you know, I'm new to Linux, Docker et all.  Few questions re the above:
1. Is there a way I can know when you release new versions of OCRmyPDF, perhaps incorporating new message?
2. Do I simply need to "Docker run OCRmyPDF" to effectively download the latest image?
3. Is there a guide to the various Info/warning messages that identify types of PDF?

Thanks
Perry

**Comment by jbarlow83** [comment]
1. I did add a new version (4.1.3) that gives an error message.
Unfortunately I can't tell anything about those PDFs at all, except that
they are encrypted. Because the contents are encrypted they cannot be
parsed for text.

I believe you can subscribe to the RSS feed for the project on Github to
get notification of new releases.

2. Use "docker pull" to update. When I release a new version it will
trigger an automatic build of the new docker image, but several hours may
pass in between depending how busy docker hub is. I have no control of
this.

3. Other than the source, no. Messages will always be sent through the
logger and the logger always has "log" in the name. You are finding some
errors not previously discovered so I can't say the error messages would be
comprehensive. There is no enumeration of types of PDFs to work with
either, just PDFs with different features.

**Comment by perrygarrod** [comment]
Hi Jim
Have just attempted to "pull" latest version but Docker reports:
Pulling repository docker.io/library/ocrmypdf
and get
Error: image library/ocrmypdf not found

**Comment by jbarlow83** [comment]
Try docker pull jbarlow83/ocrmypdf
