### ISSUE TITLE
PDF converted to PDF/A-2b still fails rule 6.3.3-2 according to veraPDF

### ISSUE THREAD

**Issue by so-o** [jbarlow83/OCRmyPDF#722]
OCRmyPDF 11.5.0 + qpdf just recompiled from Git + pikepdf 2.4.0. The PDF is quite big, ~6 MB.

https://docs.verapdf.org/validation/pdfa-parts-2-and-3/#6.3.3-2

**Comment by jbarlow83** [comment]
The error message pertains to PDFs with form widgets, which do not commonly appear in scanned image PDFs and are not manipulated by ocrmypdf in any way.

You could try using Ghostscript to manually convert the PDF to PDF/A. If Ghostscript cannot create a PDF/A-2b in this situation, ocrmypdf will not be able to either. If so, you could report the error to Ghostscript to see if they will take on the issue. We rely on Ghostscript for most aspects of PDF/A conversion; if Ghostscript can't do we can't either. (You can run `ocrmypdf -k ...` and obtain the file `pdfa.ps` which Ghostscript requires for manual PDF/A conversion.

For now I'm going to close this issue on the assumption this is a Ghostscript problem that would have to be fixed in Ghostscript. If you have more information that suggests there is something I could do to fix it, please let me know here.
