### ISSUE TITLE
Is there a way to replace fonts when generating a PDF/A?

### ISSUE THREAD

**Issue by so-o** [jbarlow83/OCRmyPDF#723]

**Comment by jbarlow83** [comment]
If you have a PDF that is failing to convert to PDF/A because it references an external font that is not embedded. This is difficult to resolve and would probably require Acrobat or low level manipulation of data structures with pikepdf.

If you use `--force-ocr` the PDF will be "flattened" to images and OCRed. This almost always fixes any font problems in a PDF.
