### ISSUE TITLE
Automatic recognition of links in OCR and creation of hyperlinks

### ISSUE THREAD

**Issue by Matthias84** [jbarlow83/OCRmyPDF#727]
**Is your feature request related to a problem? Please describe.**
I use ocrmypdf embedded with paperless-ng to scan and archive my paper documents. As such, I miss the oportunity to click on textareas with hyperlinks / domains and (esp. on mobile devices) to click at email-adresses and phone numbers. On parcels, etc. there are QR codes with trackingnumbers etc. embedded

**Describe the solution you'd like**
A flag to enable a processing step, which adds clickable hyperlinks following the http(s):, mailto:, tel: standards.

**Describe alternatives you've considered**
Manual select and copy & paste to the dedicated broser / email / caller apps work fine, but esp. on mobile devices this is getting unnecessary complicated.

**Additional context**
This might also add broken links or even more security related issues as hidden links to bad pages etc.

**Comment by jbarlow83** [comment]
This sort of feature could be implemented with a plugin or external script. It would potentially need a new plugin hook, but could also be implemented in a custom `OcrEngine.generate_pdf` if it was derived from OCR results alone. 

I can't see it being generally useful, because as you mention if there are OCR errors the links will be wrong.

QR codes could be checked for about the same stage as OCR since it is the same sort of process of finding meaning in pixel data.

**Comment by jbarlow83** [comment]
Closing: suggested plugin
