### ISSUE TITLE
Use "alternative" OCR service

### ISSUE THREAD

**Issue by gfournier** [jbarlow83/OCRmyPDF#728]
**Is your feature request related to a problem? Please describe.**
I'm working with other OCR service, like ABBY or Azure Cognitive Services to build text extraction algorithms on PDF files.
To export and visualize results we need to have a "searchable" PDF, is there a plan to add new OCR providers ? (API based for example).

**Describe the solution you'd like**
Implement new OCR provider (API based) in OCRmyPDF, I can implement the solution if you're ok.

**Describe alternatives you've considered**
Home made solution, based on existing open source software, request to vendors to provide solution.

**Comment by jbarlow83** [comment]
You could write a plugin to replace the standard OCR engine - the plugin
architecture is set up for it.

I have no plans to add other OCR services myself. Many users use ocrmypdf
because it keeps their confidential files private - so that offline OCR
will always be the default. I also won't do work that generates revenue for
a cloud service provider unless I'm compensated for the effort - they have
lots of money already.

**Comment by gfournier** [comment]
Ok thanks, I will have a look at the plugin architecture.
