### ISSUE TITLE
`ocrmypdf` generates corrupt `tif`s which effectively disables `jbig2` to process

### ISSUE THREAD

**Issue by Iey4iej3** [jbarlow83/OCRmyPDF#732]
**Describe the bug**
The pdf is not generated. Seemingly, the `ocrmypdf` generates corrupt `tif` files which could not be processed by `jbig2` (I succeeded to compress the file by [pdfsizeopt](https://github.com/pts/pdfsizeopt)).

**To Reproduce**
``` bash
ocrmypdf -k --pages 1 --output-type pdf --skip-text --tesseract-timeout 0 test.pdf test.ocr.pdf
```

**Example file**
[Link](https://www.dropbox.com/s/rqkdf3bga0n5n3y/test.pdf.gpg?dl=0)
**Disclaimer:** One should not distribute this file.

**System**
 - OS: Debian Buster
 - OCRmyPDF Version: 11.6.0
 - How did you install ocrmypdf: pip

**Comment by Iey4iej3** [comment]
@jbarlow83 Another file with the same issue reproducible under 11.7.2: https://www.dropbox.com/s/a9mli89dbwfvpy6/test.pdf.gpg?dl=0

**Comment by jbarlow83** [comment]
Thanks for the report. Your new file contains images encoded in CCITT Group 3, and outdated compression scheme that does not seem to be well supported by underlying libraries.

I'll release a fix shortly for ocrmypdf that will skip optimization of Group 3 images. Supporting optimization of Group 3 will probably take longer because it's not widely used.

`--force-ocr` will rasterize the images with Ghostscript (which can decode them) and then reencode them in a modern more format. For older files with quirks and which are scanned images this is probably ideal - look at this vector, there doesn't seem to be any vector content, so force OCR doesn't lose anything.

Note to self: local name for second file is issue732_2.pdf.

**Comment by jbarlow83** [comment]
11.7.3 should work around the issue.
