### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by izahn** [jbarlow83/OCRmyPDF#738]
**Is your feature request related to a problem? Please describe.**

OCRmyPDF has many dependencies (e.g., pngquant, unpaper) making installation difficult.

**Describe the solution you'd like**

I want to `conda install ocrmypdf`

**Describe alternatives you've considered**

Right now I use ocrmypdf via singularity on my University's HPC cluster. It works OK, but the extra layer of indirection makes scripting more difficult.

**Additional context**

I have packaged all OCRmyPDF dependencies for conda-forge, and submitted a package for OCRmyPDF itself at https://github.com/conda-forge/staged-recipes/pull/14066

If there is anyone here who would like to join me as a co-maintainer of the conda-forge package I would be delighted to add you!

**Comment by jbarlow83** [comment]
Thanks for creating a conda wrapper for ocrmypdf.

I'll close this for now, because I don't think there's anything I can do personally to help with maintaining this package, and if anyone searches for "conda" and ocrmypdf they'll be able to follow the trail you've left.

If/when the conda recipe(?) is formally accepted please open a PR to add this to the installation documentation.
