### ISSUE TITLE
Error when the --sidecar argument without FILE is the last argument before input & output

### ISSUE THREAD

**Issue by veikk0** [jbarlow83/OCRmyPDF#746]
The help output for `--sidecar` states:

>If FILE is omitted, the sidecar file be named {output_file}.txt

However, this feature only works if `--sidecar` isn't the last argument before the input file. When placed directly before the input file, `--sidecar` assumes the input as its output value, input becomes output, and there is no actual output file from the program's point of view. In such a case, OCRmyPDF outputs the following error:

>ocrmypdf: error: the following arguments are required: output_pdf

Essentially, when used without defining the output file, `--sidecar` is a positional argument.

**To Reproduce**
`ocrmypdf --output-type pdf --sidecar input.pdf output.pdf`

**System (please complete the following information):**
 - OS: Linux Mint 20.1
 - Python version:3.8.5
 - OCRmyPDF version: 11.7.0

**Installation**
Installed from pip

**Comment by jbarlow83** [comment]
What currently happens is standard behavior for command line parsing. An argument with a parameter will consume the subsequent token: `--sidecar` consumes the next token on the command line, unless it begins with `-`. Because it consumes the next token, `output.pdf` looks like the input file, and there is no output file.

You would use `ocrmypdf --output-type pdf --sidecar -- input.pdf output.pdf` to suppress interpretation of `input.pdf` as the argument to `--sidecar`.

I updated the documentation to explain this a little better and prevent making the sidecar equal to the input or output file.
