### ISSUE TITLE
Check for leptonica liblept at runtime, not at import

### ISSUE THREAD

**Issue by GLeurquin** [jbarlow83/OCRmyPDF#779]
**Is your feature request related to a problem? Please describe.**
Importing `ocrmypdf` imports `leptonica`, which checks if `liblept` is present and throws a `MissingDependencyError` if it is not found. In my case, I'm not using the tesseract part of this module, as I'm using another backend, and I don't want to install tesseract & leptonica on the environment (aws lambda).

**Describe the solution you'd like**
Only check for `liblept` when `leptonica` module is actually used, not when it is imported. Another suggestion would be to allow more easily to use a different backend for the ocr and make tesseract & leptonica optional or even to provide our own OCR output that can then be used as usual in the rest of the ocrmypdf pipeline.

**Describe alternatives you've considered**
Currently the only alternative is to fork this project and remove the check in the leptonica file, as the `leptonica` module is imported in ` __init__.py` and also in other modules.

**Additional context**
In my case I'm using google vision as a backend instead of tesseract. This package is great, but it would be nice if it could allow some kind of "api" for the ocr part instead of forcing it to be tesseract. The part to graft text on the pdf and optimizing the pdf is especially useful.

**Comment by jbarlow83** [comment]
You can use a plugin to replace the OCR engine with your version. See `tests/plugins/` for this being done to replace Tesseract for testing purposes.

Leptonica is used for certain other features like `--deskew`. I marked the library as deprecated because it's an ABI binding to a C library that causes a variety of complications. I have not decided how to replace it. I have considering using spinning it off into a separate project that presents a clean Python interface, or replace with another image library.

For now I recommend removing the module in a fork if you don't need it.

**Comment by jbarlow83** [comment]
Fixed for v13 (note: currently a pre-release) by removing leptonica entirely.

**Comment by jbarlow83** [comment]
Note that ocrmypdf in v13 will use Tesseract to calculate the skew angle for deskewing, but if you write your OCR backend as a plugin, you can teach it how to get the skew angle from Google Vision or any source, or retain Tesseract for this purpose.
