### ISSUE TITLE
OCR'ed file much bigger than original

### ISSUE THREAD

**Issue by Jmuccigr** [jbarlow83/OCRmyPDF#79]
Here's an example of an original 236k file becoming 1MB after OCR.
[Develin - 1977 - Comitia Tributa Again.pdf](https://github.com/jbarlow83/OCRmyPDF/files/366993/Develin.-.1977.-.Comitia.Tributa.Again.pdf)
[60751.pdf](https://github.com/jbarlow83/OCRmyPDF/files/366994/60751.pdf)

**Comment by jbarlow83** [comment]
**Analysis**

There's an ICC profile attached to the monochrome image in the input file, which is not common but useful for PDFs that want to define how light the paper is or how dark the black is. The code was written to assume unusual images are full color unless it can prove otherwise. I've added a fix to handle monochrome-ICC images better although it will work incorrectly if the ICC profile happens to define a colorspace other than black/white.

Because the PDF already contains some text (the header/footer) it's not eligible for lossless reconstruction and needs `--force-ocr`. The PDF producer is Apache FOP 1.0 (Formatting Objects Processor) which is not the test suite.

Because of `--force-ocr`, we need to reconstruct the image layer using img2pdf and the hocr renderer, the former of which is not capable of rendering monochrome images and promotes the image to grayscale, so the size still increases. Implementing monochrome for img2pdf is a possibility; pdfminer seems to have a Python CCITT implementation and permissive license.

`--force-ocr --pdf-renderer tesseract` uses the tesseract renderer. Overall the tesseract renderer is better, but its way of encoding causes problems for certain PDF viewers (OS X Preview being the worst). Some viewers will fail to extract text via copy/paste or the PDF will not be searchable because words are not properly segmented. The underlying problem is that the PDF spec does not define spaces between words so viewers use a heuristic to segment them, and some do a better job (Acrobat) than others (OS X Preview). Fonts with narrow kerning are particularly problematic.

**Suggested solution**
* Upgrade to ocrmypdf 4.1.4 (-rc1 release with the fix), tesseract 3.04.01 – consider using tesseract 3.05.dev  
* Use `ocrmypdf --force-ocr --pdf-renderer tesseract` and check that the file works correctly (search, copy/paste) in your favorite PDF viewer. The provided file seems to work for me.

**Comment by Jmuccigr** [comment]
I've already got tesseract 3.04.01, so I'll try getting the RC of ocrmypdf and see what happens.

Out of curiosity:

> Because the PDF already contains some text (the header/footer) it's not eligible for lossless reconstruction and needs --force-ocr.

Why is this?

**Comment by jbarlow83** [comment]
Vector text objects in a PDF can represent either printable text or a
hidden OCR layer. At the moment if vector text objects are found ocrmypdf
exists on an error, because this needs user input. It could mean that the
file is "born digital" and OCR will degrade quality because the text is
100% recognized, or it could mean another program did OCR already and
redoing it not necessarily what the user wants.

The two options are: skipping text pages, useful if you have a PDF with a
mix of born digital and scanned content; and force OCR which rasterizes all
vector objects so is quite lossy. --skip-text is lossless but will do
nothing in the case of your file.

It's doable but not trivial to distinguish between printable and hidden
text so at the moment ocrmypdf just checks if there is any text on a page.
The way OCR text is represented in PDF is an afterthought. Future versions
could make this distinction.

**Comment by Jmuccigr** [comment]
I guess my question comes back to why the original image can't be combined with the new text. A Windows app I use (at work) can delete text "layers" so that a new round of OCR creates a new one, for example.

**Comment by jbarlow83** [comment]
ocrmypdf doesn't extract the images because there can be multiple images per page at any arbitrary position, rotation and dimension. To get the layout right it rasterizes the whole page, runs OCR, and then grafts the text layer into the original PDF (where possible). 

You have a vector text watermark that makes for a rare edge case and I have a partial solution for that via `--force-ocr` that gets you almost everything you want, with the small shortcoming of applying to OCR to the header text. The hard answer to the problem involves editing the PDF content stream to filter out printing text; I don't think that's worth the effort. I am looking into whether or not there's an easy answer, like forcing Ghostscript to substitute all fonts with a null font.

Acrobat can derive a virtual text layer (PDF has no concept of layers, it has derive it). It took Acrobat ten versions to this feature, because it's a difficult feature to implement.

**Comment by Jmuccigr** [comment]
I suppose I'm after having ocrmypdf do what commercial solutions that I use do: leave the image alone and add the text to it.

**Comment by jbarlow83** [comment]
ocrmypdf does leave the image alone and add text. It just cannot pull that trick on files that already have vector text, unless you permit it to rasterize the vector text. 

The content stream is a graphics programming language based on Postscript. Many operations are context-sensitive and involve relative positioning – so it's not trivial to strip out printing text and put it back in. Doable, not trivial. It's nothing like HTML where markup groups related elements or CSS where rules can be applied to all elements matching a selector.

Commercial solutions are likely interpreting the content stream, building an abstract representation of it, and serializing it after editing. The new content stream is usually completely rewritten.

**Comment by jbarlow83** [comment]
I submitted a change to img2pdf that should further reduce the image size. You can install the HEAD revision with (from memory) ``pip install --upgrade git+http://gitlab.mister-muffin.de/josch/img2pdf.git`` - it is not in any released version as yet.

**Comment by jbarlow83** [comment]
The specific issue of monochrome images being forced up to grayscale was resolved a while back. Improvements to avoid rasterizing visible text will come in future releases.
