### ISSUE TITLE
Feature Request --nocheckdependencies

### ISSUE THREAD

**Issue by AntonioSoler** [jbarlow83/OCRmyPDF#791]
We are using this to process thousands of documents and we can read on the log (with verbose 1) that tesseract is launched twice (once to check the available languages and another one to check its version) and GhostScript is also launched to check its version. 

Where this would make sense for single or little batches of documents to ensure that all dependencies are installed on large scale batch processing  (100k documents) this means trashing some precious seconds of CPU and memory management just to launch a program to check its version or if it is installed.

My suggestion is to allow the use of a parameter as mentioned "--nocheckdependencies" that would skip that check and assume that latest versions of all dependencies are available.

**Comment by jbarlow83** [comment]
I believe that the cost of these tests is negligible and they are necessary because some released versions of Ghostscript in particular are defective or require workarounds. If you have some evidence that there's a significant impact I'd definitely be willing to make a change.

If you're looking for other ideas to improve performance drop me a line at james@purplerock.ca with some details and perhaps we can discuss and see if there's a way I can help with your project.
