### ISSUE TITLE
New option with python autocorrect package to improve OCR-ed text result

### ISSUE THREAD

**Issue by Kors1981** [jbarlow83/OCRmyPDF#804]
My OCR extraction has some errors like: "iducation", which would be great to be automatically corrected to "education".
I found the next python package, which would do the job.
Would be great to have such an extension in this project.

AutoCorrect reference:
https://github.com/filyp/autocorrect

**Comment by jbarlow83** [comment]
This sort of improvement belongs in the Tesseract OCR engine rather than ocrmypdf. Our job is to render the content Tesseract produces, not second-guess it.

Tesseract does have language dictionaries, it just seems to be strongly biased towards reporting "what it sees" rather than correcting text to the closest dictionary words.
