### ISSUE TITLE
Tesseract 5.0 support

### ISSUE THREAD

**Issue by zufj** [jbarlow83/OCRmyPDF#819]
As Tesseract 5.0 is nearing release (they just announced their release candidate), I was curious: will OCRmyPDF be able to support it out of the box or a new version will be required?

I'd be happy to so some testing in any case.

RC: https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.0-beta-20210815

Installation instructions: https://tesseract-ocr.github.io/tessdoc/Installation.html

**Comment by jbarlow83** [comment]
Didn't realize it was going to be out soon.
Anyway, I changed the test workflow to test the tesseract-ocr-devel PPA, which picks up 5.x, and everything already passes. So 5.0 should be fine out of box barring last minute breakage.

Not a big surprise to me, since the vast majority of work on 5.x was converting it to modern C++, and we use as a command line application.

**Comment by jbarlow83** [comment]
I'll close this for now, but if you happen to find 5.0-specific issues please open a new issue.

**Comment by homocomputeris** [comment]
Just in case: it's been released
https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.0
