### ISSUE TITLE
Documentation: Typo "performs on OCR on the rasterized image" in "What OCRmyPDF does"

### ISSUE THREAD

**Issue by Chealer** [jbarlow83/OCRmyPDF#829]
**Describe the bug**
[Section _What OCRmyPDF does_](https://ocrmypdf.readthedocs.io/en/latest/introduction.html#what-ocrmypdf-does) contains:

> It uses Ghostscript to rasterize the page, and then performs on OCR on the rasterized image to create an OCR “layer”.

"performs on OCR on the rasterized image" should read just "performs OCR on the rasterized image".

**To Reproduce**
This does not report a behavioral bug.

**Expected behavior**
This does not report a behavioral bug.

**System (please complete the following information):**
 - OS: N/A
 - Python version: N/A
 - OCRmyPDF version: 12.4.0

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's package manager, or using pip? N/A

**Additional context**
By the way, in section _About PDFs_ (a little earlier), "a good formats" should read "a good format".

**Comment by Chealer** [comment]
The "on" which should be removed is the one **before** "OCR". The sentence should read:

> It uses Ghostscript to rasterize the page, and then performs OCR on the rasterized image to create an OCR “layer”.

**Comment by Chealer** [comment]
> Yes. My time is the most precious thing in the world to me, and I will not waste it on following the inefficient you want to use.

What?

> The norm of the open source community is to use pull requests to communicate changes. 

There are many open source communities, and most probably don't even know what a "pull request" is. If I understand what you mean by "communicating changes", as my organization has no access to the relevant repository to my knowledge, I have opted for reporting issues rather than sharing commits which - as I wrote - do not even exist at this time. If your community is willing to provide us the means to fix issues efficiently, that would be welcome, but that will not invalidate other forms of contributions.

> If your organization does not follow the norm, their policy is wrong and should be changed so that employees like you can contribute constructively rather than wasting the time of volunteers with whom you have no contractual relationship.

If that is how you perceive our contribution, I suggest you take a break. If that doesn't improve your perception, I recommend you to verify that the community is comfortable with your manners, and if so, to change the issue tracker to warn that issues are not tracked methodically.

**Comment by jbarlow83** [comment]
@Chealer Please refer to the Github documentation to follow the normal and efficient procedure for making small changes to documentation. I am happy to consider contributions that are submitted using the Github Pull Request feature. Using this workflow you can easy make small changes to documentation:
https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files

Please do not open new issues for small changes to documentation.

I do welcome contributions. You may note that several of your suggestions were previously accepted, the same reason for which this issue was closed, and I advised you to contribute them in a way that saves us both time.
