### ISSUE TITLE
Output PDFs cropped when image DPI is not square

### ISSUE THREAD

**Issue by efowler** [jbarlow83/OCRmyPDF#83]
We have come across a few PDFs that are throwing us for a loop. 
When looking at them in Acrobat and Preview (on the Mac), they look like they're in portrait.
In Photoshop they look landscape.  

When calling:

`ocrmypdf printsize.pdf output.pdf`

The content is then cropped (not resized), to landscape. No doubt it's a weird file, but wondering what can be done to retain the content of the pdf? 

I've redacted the problematic pdf, and attached it below.
[printsize.pdf](https://github.com/jbarlow83/OCRmyPDF/files/389049/printsize.pdf)

Thanks!

**Comment by jbarlow83** [comment]
The image resolution in your sample is not "square". It's 200x100 DPI. I was actually just working on fixing some a similar issue related to this and should have a fix out shortly.

If you're in a hurry ImageMagick can resample images to change their pixel density.

**Comment by efowler** [comment]
Ah good to hear it's already on the radar.  Yeah i'll investigate resampling the images with imagemagick a little more.  Thanks!

**Comment by jbarlow83** [comment]
Fixed in v4.2.

If using `--pdf-renderer tesseract` the image will be resampled to square resolution because this rendering path does not understand non-square images. `--pdf-renderer hocr` will keep the original image resolution and generate a square resolution image when needed.

I'm on the fence as to whether to force all content to this; it increases file sizes but a number of other image programs struggle with non-square images.
