### ISSUE TITLE
Provide Python APIs

### ISSUE THREAD

**Issue by mlissner** [jbarlow83/OCRmyPDF#85]
This is a follow on to issue #18, which wanted documentation for Python APIs. Alas, such APIs aren't formalized, so documenting them wouldn't make sense.

So...let's formalize the API and then we can provide documentation for it.

**Comment by jbarlow83** [comment]
The big question is, what do you want to do with the API? 

The ruffus library's decorators decide what functions in the pipeline to activate at module import time, and after that the pipeline is fixed, and it's all decided based on `sys.args`. That is an unfortunate quirk and it also restricts the capabilities of the test suite; it can inspect output files but not the state of Python objects between pipeline stages for example. This is an actual barrier to usage as an API.

The options are to change to change to the [ruffus "object oriented API"](http://www.ruffus.org.uk/tutorials/new_syntax_worked_example.html). This is largely a mechanic change of rewriting the function @decorators.

Another I'm considering is switching from ruffus to an asyncio based pipeline. I like this option because there are probably already more people who understand asyncio than ruffus. It would also  solve the issues of marshalling exception objects and logging data across process boundaries when errors happen, something ruffus and Python are both not good at. It would get full CPU usage from process pools and I/O multiplexing.

**Comment by mlissner** [comment]
I don't know the first thing about ruffus, so most of that is greek to me, but I think (*think*) I have two use cases in mind:

1. Super-simple OCR work.
2. Mondo-performance sensitive OCR work.

For the first, I just want an API that I can use to avoid having to use `subprocess` in my Python code. Something super simple where I say, "Here's my PDF, here's where I want the OCR'ed PDF, here are some options about how I want it done."

The second one is more complicated, and I suspect you'll have better ideas here than I do, but I'm presently using Celery to process about 4M PDFs, and I'd love something that allowed the CPU and process pooling you're discussing while using Celery. That might not be possible, I don't know.

An API like this would also make sense:

```python
ocr_options = {'lang': 'eng', 'something': 'else'}
ocr_pool = OCRPool(options=options)
for p in glob.glob('/path/to/pdfs*'):
    ocr_pool.enqueue(p)
ocr_pool.go()
ocr_pool.join()
print("Finished doing OCR")
```

That's off the top of my head, but it feels like the kind of API I'd expect.

**Comment by jbarlow83** [comment]
Thanks, that gives me some ideas.

ocrmypdf uses ruffus to parallelize the OCR of each page on its own unless asked not to.

I don't think I would get into managing OCR jobs. It seems like if I provide a good `ocrmypdf(filename, options)` it's not hard to wrap job control around that, but everyone will need to do it a little differently depending on their framework.

**Comment by mlissner** [comment]
Yeah, that makes sense to keep it simple. I just don't know if the pooling and I/O multiplexing would work that way. For me, that's a huge feature this library promises.

**Comment by zorglups** [comment]
I second mlissner.
Having a simple wrapper (ocrmypdf(filename, options)) would be really nice.
