### ISSUE TITLE
Issue while installing as non admin user

### ISSUE THREAD

**Issue by shadylpstan** [jbarlow83/OCRmyPDF#854]
**Describe the bug**
After installing tesseract and ghostscript through chocolatey as non admin user,  OCRmyPDF isn't able to look for ghostscript and tesseract.

**To Reproduce**
Install chocolaty as non admin proceedure.
Install tesseract and ghostscript.
Set env path to tesseract and ghostscript (since they as installed in different location as non admin)
Run OCRmyPDF to convert a pdf.
OCRmyPDF gives an error that it cannot find tesseract.
Type tesseract in command window, and it will work. But not through OCRmyPDF

**Expected behavior**
OCRmyPDF should convert the pdf without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14815653/140912496-a5c1e28d-23fc-4824-a8fe-0a6ad7303942.png)

**System (please complete the following information):**
 - OS: Window 10
 - Python version: 3.7
 - OCRmyPDF version:12.7.2

**Installation**
Installed through pip.
Chocolaty and other dependencies through powershell as NON ADMIN

**Comment by jbarlow83** [comment]
As far as I know chocolatey doesn't work well if you're not admin. The Linux package managers also don't work properly without sudo. As long as you can install as admin, there is not really an issue from my perspective.

You may be able to manually manipulate your user PATH environment variable so that Ghostscript and Tesseract can be found.

**Comment by BenjaminHoegh** [comment]
Is it possible to tell OCRmyPDF to use a specific path instead of the PATH environment?
