### ISSUE TITLE
Where is the debug file?

### ISSUE THREAD

**Issue by varna9000** [jbarlow83/OCRmyPDF#860]
I'm using OCRmyPDF from command line. 
I got verbosity argument `-v 1` set but I can't find where the debug file is written (if any). Can I set location of the debug file if I'm using CLI?

**Comment by jbarlow83** [comment]
You need to run with `-k` as well to keep temporary temporary files. The log file is stored in temp files. With this option, when finished (success or failure), the path of the temporary folder will be printed. Otherwise the temporary folder is deleted.

The location of the log file cannot be changed without scripting. It's always in the temporary folder. This ensures that parallel ocrmypdf processes do not compete for write access to the same log file.

You could also use your operating system's tools to inspect the ocrmypdf process and obtain the name of its temporary folder, if you want to inspect a long running process.
