### ISSUE TITLE
Changing rendered font

### ISSUE THREAD

**Issue by Leland** [jbarlow83/OCRmyPDF#861]
Hello there! Love this project, thanks so much for the hard work :) Apologies in advance for my limited understanding of the project – if this is a question meant more for the Tesseract repo, please close!

I'm working on a PDF that uses a specific font. When using the `sandwich` renderer, text selection runs just a little ragged. 

I'm not looking to train on a new font – the actual OCR'd text is good. **I'm trying to get the selectable text to more closely fit the underlying block of text's bounding box.**

I'm working on figuring this out myself, but figured I'd ask here as well: is it a fool's errand to try to get OCRmyPDF to do this? I suspect from some skimming of the code that an actual font's glyphs (Helvetica?) are used to determine things like kerning and character width, so it would follow that one _should_ be able to override that. I have the font in question.

!['I'm not making you dinner' is shown inside a text bubble](https://user-images.githubusercontent.com/714017/142433446-bf02ff8c-48c0-471d-bded-63ffad507d42.png)

**System**
* OS: macOS 12
* OCRmyPDF Version: 12.7.2
* Homebrew install

**Comment by jbarlow83** [comment]
If you have the true font you'll be able to closer alignment but not perfect. Tesseract provides bounding boxes for words, but does not provide coordinates for typesetting at the glyph level. It would need another level of OCR, i.e. finding a perfect font match and then figuring out how to position each glyph in that font. Tesseract is not trained to identify specific fonts in this way, at least not to my knowledge.

reportlab's documentation has some instructions on adding a non-PDF-standard font. You can't just name it, you have to actually tell reportlab where the filepath is so it gets properly embedded.

Text selection appears differently on different PDF viewers and getting it to look right on all can be tricky. macOS Preview.app is particularly obstinate. Generally it does work better with a real font rather than sandwich's glyphless font which is a hack.

**Comment by Leland** [comment]
Got it, that's probably enough for me to do my own research into! Thanks :)
