### ISSUE TITLE
ocrmypdf requires old pikepdf

### ISSUE THREAD

**Issue by navtis** [jbarlow83/OCRmyPDF#863]
OCRmyPDF  12.7.2 (on gentoo, installed from an unofficial overlay at https://data.gpo.zugaina.org/guru/app-text/OCRmyPDF/ ) fails to start, complaining that the system pikepdf version is 4.0.2 but that OCRmyPDF will only accept pikepdf versions between 1.14 and 3.  It used to work, which is odd as the oldest pikepdf in Gentoo is 3.2, which no longer works with OCRmyPDF, giving the same error.

Is there any chance that OCRmyPDF will work with pikepdf > 3.0 in the near future? 

There are similar problems with the stock gentoo dev-python/pluggy and dev-python/setuptools_scm which need to be held back to old versions for OCRmyPDF

**Comment by jbarlow83** [comment]
The linked overlay seems to use ocrmypdf 12.0.2 (dated May 2021) not 12.7.2. 12.0.2 does have tighter restrictions since it predates pikepdf 3.

ocrmypdf 12.7.2 permits pikepdf >= 2.10.0; pikepdf 3 and 4 are supported, except in the specific case of pypy 3.6 which requires pikepdf < 3. Perhaps someone misread that narrow exception?

pluggy 1.0 was approved in v12.4.0.
There's no version restriction on setuptools_scm?

**Comment by navtis** [comment]
The current overlay is now 12.6.0, which seems to be fine. Also, I had misconfigured my sync with the overlay site, and wasn't actually fetching the latest version, to add to the confusion. Everything now seems to be working for gentoo. Thanks!
