### ISSUE TITLE
Runtime dependency on pkg_resources

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#87]
ocrmypdf needs the pkg_resources module.  So far as I can tell that comes from setuptools.  Shouldn't that be listed in install_requires in setup.py?

**Comment by jbarlow83** [comment]
The official Python includes setuptools and pkg_resources in the standard library, but some Linux flavors including Debian exclude it because it's not necessary for non-developers.

You can't install from source without setuptools because `setup.py` calls `from setuptools import...`. I thought about replacing this with an error message but searching for the error message `ImportError: No module named 'setuptools'` will steer people towards platform specific answers (browsers broadcast the platform in headers). So I think failing with the default error message is the best option.

**Comment by spwhitton** [comment]
On Thu, Aug 25, 2016 at 02:11:48PM -0700, jbarlow83 wrote:
> The official Python includes setuptools and pkg_resources in the standard
> library, but some Linux flavors including Debian exclude it because it's not
> necessary for non-developers.
> 
> You can't install from source without setuptools because setup.py calls from
> setuptools import.... I thought about replacing this with an error message but
> searching for the error message ImportError: No module named 'setuptools' will
> steer people towards platform specific answers (browsers broadcast the platform
> in headers). So I think failing with the default error message is the best
> option.

Okay, I'll just keep the manually added dependency.  Thanks.

-- 
Sean Whitton
